
// Generated by Cadence Genus(TM) Synthesis Solution 19.12-s121_1
// Generated on: Feb  1 2022 11:52:54 IST (Feb  1 2022 06:22:54 UTC)

// Verification Directory fv/fifo 

module fifo(rdata, wfull, rempty, wdata, winc, wclk, wrst_n, rinc,
     rclk, rrst_n);
  input [7:0] wdata;
  input winc, wclk, wrst_n, rinc, rclk, rrst_n;
  output [7:0] rdata;
  output wfull, rempty;
  wire [7:0] wdata;
  wire winc, wclk, wrst_n, rinc, rclk, rrst_n;
  wire [7:0] rdata;
  wire wfull, rempty;
  wire [7:0] \fifomem_mem[0] ;
  wire [7:0] \fifomem_mem[1] ;
  wire [7:0] \fifomem_mem[2] ;
  wire [7:0] \fifomem_mem[3] ;
  wire [7:0] \fifomem_mem[4] ;
  wire [7:0] \fifomem_mem[5] ;
  wire [7:0] \fifomem_mem[6] ;
  wire [7:0] \fifomem_mem[7] ;
  wire [7:0] \fifomem_mem[8] ;
  wire [7:0] \fifomem_mem[9] ;
  wire [7:0] \fifomem_mem[10] ;
  wire [7:0] \fifomem_mem[11] ;
  wire [7:0] \fifomem_mem[12] ;
  wire [7:0] \fifomem_mem[13] ;
  wire [7:0] \fifomem_mem[14] ;
  wire [7:0] \fifomem_mem[15] ;
  wire [3:0] waddr;
  wire [3:0] raddr;
  wire [4:0] wq2_rptr;
  wire [4:0] rq2_wptr;
  wire [4:0] wptr;
  wire [4:0] rptr;
  wire [4:0] sync_r2w_wq1_rptr;
  wire [4:0] sync_w2r_rq1_wptr;
  wire n_589, n_590, n_591, n_592, n_593, n_594, n_595, n_596;
  wire n_597, n_598, n_599, n_600, n_601, n_602, n_603, n_604;
  wire n_605, n_606, n_607, n_608, n_609, n_610, n_611, n_612;
  wire n_613, n_614, n_615, n_616, n_617, n_618, n_619, n_620;
  wire n_621, n_623, n_626, n_629, n_631, n_635, n_638, n_642;
  wire n_646, n_647, n_648, n_649, n_650, n_651, n_652, n_653;
  wire n_654, n_655, n_656, n_657, n_658, n_659, n_660, n_661;
  wire n_662, n_663, n_664, n_665, n_666, n_675, n_676, n_677;
  wire n_678, n_684, n_691, n_692, n_693, n_754, n_755, n_756;
  wire n_757, n_758, n_759, n_760, n_761, n_762, n_763, n_764;
  wire n_765, n_766, n_767, n_768, n_769, n_770, n_771, n_772;
  wire n_773, n_774, n_775, n_776, n_777, n_778, n_779, n_780;
  wire n_781, n_782, n_783, n_844, n_845, n_846, n_847, n_848;
  wire n_849, n_850, n_851, n_852, n_853, n_854, n_855, n_856;
  wire n_857, n_858, n_859, n_860, n_861, n_862, n_863, n_864;
  wire n_865, n_866, n_867, n_868, n_869, n_870, n_871, n_872;
  wire n_873, n_934, n_935, n_936, n_937, n_938, n_939, n_940;
  wire n_941, n_942, n_943, n_944, n_945, n_946, n_947, n_948;
  wire n_949, n_950, n_951, n_952, n_953, n_954, n_955, n_956;
  wire n_957, n_958, n_959, n_960, n_961, n_962, n_963, n_1024;
  wire n_1025, n_1026, n_1027, n_1028, n_1029, n_1030, n_1031, n_1032;
  wire n_1033, n_1034, n_1035, n_1036, n_1037, n_1038, n_1039, n_1040;
  wire n_1041, n_1042, n_1043, n_1044, n_1045, n_1046, n_1047, n_1048;
  wire n_1049, n_1050, n_1051, n_1052, n_1053, n_1114, n_1115, n_1116;
  wire n_1117, n_1118, n_1119, n_1120, n_1121, n_1122, n_1123, n_1124;
  wire n_1125, n_1126, n_1127, n_1128, n_1129, n_1130, n_1131, n_1132;
  wire n_1133, n_1134, n_1135, n_1136, n_1137, n_1138, n_1139, n_1140;
  wire n_1141, n_1142, n_1143, n_1204, n_1205, n_1206, n_1207, n_1208;
  wire n_1209, n_1210, n_1211, n_1212, n_1213, n_1214, n_1215, n_1216;
  wire n_1217, n_1218, n_1219, n_1220, n_1221, n_1222, n_1223, n_1224;
  wire n_1225, n_1226, n_1227, n_1228, n_1229, n_1230, n_1231, n_1232;
  wire n_1233, n_1294, n_1295, n_1296, n_1297, n_1298, n_1299, n_1300;
  wire n_1301, n_1302, n_1303, n_1304, n_1305, n_1306, n_1307, n_1308;
  wire n_1309, n_1310, n_1311, n_1312, n_1313, n_1314, n_1315, n_1316;
  wire n_1317, n_1318, n_1319, n_1320, n_1321, n_1322, n_1323, n_1384;
  wire n_1385, n_1386, n_1387, n_1388, n_1389, n_1390, n_1391, n_1392;
  wire n_1393, n_1394, n_1395, n_1396, n_1397, n_1398, n_1399, n_1400;
  wire n_1401, n_1402, n_1403, n_1404, n_1405, n_1406, n_1407, n_1408;
  wire n_1409, n_1410, n_1411, n_1412, n_1413, n_1416, n_1419, n_1458;
  wire n_1459, n_1460, n_1461, n_1462, n_1463, n_1464, n_1465, n_1466;
  wire n_1467, n_1468, n_1469, n_1508, n_1509, n_1510, n_1511, n_1512;
  wire n_1513, n_1514, n_1515, n_1516, n_1517, n_1518, n_1519, n_1541;
  wire n_1542, n_1543, n_1544, n_1545, n_1546, n_1547, n_1548, n_1549;
  wire n_1550, n_1551, n_1552, n_1553, n_1554, n_1555, n_1556, n_1557;
  wire n_1558, n_1559, n_1560, n_1561, n_1562, n_1563, n_1564, n_1565;
  wire n_1566, n_1567, n_1568, n_1569, n_1570, n_1571, n_1572, n_1573;
  wire n_1574, n_1575, n_1576, n_1577, n_1578, n_1579, n_1580, n_1581;
  wire n_1582, n_1583, n_1584, n_1585, n_1586, n_1587, n_1588, n_1589;
  wire n_1590, n_1591, n_1592, n_1593, n_1594, n_1595, n_1596;
  CDN_flop \fifomem_mem_reg[0][0] (.clk (wclk), .d (wdata[0]), .sena
       (n_1582), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[0] [0]));
  CDN_flop \fifomem_mem_reg[0][1] (.clk (wclk), .d (wdata[1]), .sena
       (n_1582), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[0] [1]));
  CDN_flop \fifomem_mem_reg[0][2] (.clk (wclk), .d (wdata[2]), .sena
       (n_1582), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[0] [2]));
  CDN_flop \fifomem_mem_reg[0][3] (.clk (wclk), .d (wdata[3]), .sena
       (n_1582), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[0] [3]));
  CDN_flop \fifomem_mem_reg[0][4] (.clk (wclk), .d (wdata[4]), .sena
       (n_1582), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[0] [4]));
  CDN_flop \fifomem_mem_reg[0][5] (.clk (wclk), .d (wdata[5]), .sena
       (n_1582), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[0] [5]));
  CDN_flop \fifomem_mem_reg[0][6] (.clk (wclk), .d (wdata[6]), .sena
       (n_1582), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[0] [6]));
  CDN_flop \fifomem_mem_reg[0][7] (.clk (wclk), .d (wdata[7]), .sena
       (n_1582), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[0] [7]));
  CDN_flop \fifomem_mem_reg[1][0] (.clk (wclk), .d (wdata[0]), .sena
       (n_1579), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[1] [0]));
  CDN_flop \fifomem_mem_reg[1][1] (.clk (wclk), .d (wdata[1]), .sena
       (n_1579), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[1] [1]));
  CDN_flop \fifomem_mem_reg[1][2] (.clk (wclk), .d (wdata[2]), .sena
       (n_1579), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[1] [2]));
  CDN_flop \fifomem_mem_reg[1][3] (.clk (wclk), .d (wdata[3]), .sena
       (n_1579), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[1] [3]));
  CDN_flop \fifomem_mem_reg[1][4] (.clk (wclk), .d (wdata[4]), .sena
       (n_1579), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[1] [4]));
  CDN_flop \fifomem_mem_reg[1][5] (.clk (wclk), .d (wdata[5]), .sena
       (n_1579), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[1] [5]));
  CDN_flop \fifomem_mem_reg[1][6] (.clk (wclk), .d (wdata[6]), .sena
       (n_1579), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[1] [6]));
  CDN_flop \fifomem_mem_reg[1][7] (.clk (wclk), .d (wdata[7]), .sena
       (n_1579), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[1] [7]));
  CDN_flop \fifomem_mem_reg[2][0] (.clk (wclk), .d (wdata[0]), .sena
       (n_1578), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[2] [0]));
  CDN_flop \fifomem_mem_reg[2][1] (.clk (wclk), .d (wdata[1]), .sena
       (n_1578), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[2] [1]));
  CDN_flop \fifomem_mem_reg[2][2] (.clk (wclk), .d (wdata[2]), .sena
       (n_1578), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[2] [2]));
  CDN_flop \fifomem_mem_reg[2][3] (.clk (wclk), .d (wdata[3]), .sena
       (n_1578), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[2] [3]));
  CDN_flop \fifomem_mem_reg[2][4] (.clk (wclk), .d (wdata[4]), .sena
       (n_1578), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[2] [4]));
  CDN_flop \fifomem_mem_reg[2][5] (.clk (wclk), .d (wdata[5]), .sena
       (n_1578), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[2] [5]));
  CDN_flop \fifomem_mem_reg[2][6] (.clk (wclk), .d (wdata[6]), .sena
       (n_1578), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[2] [6]));
  CDN_flop \fifomem_mem_reg[2][7] (.clk (wclk), .d (wdata[7]), .sena
       (n_1578), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[2] [7]));
  CDN_flop \fifomem_mem_reg[3][0] (.clk (wclk), .d (wdata[0]), .sena
       (n_1580), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[3] [0]));
  CDN_flop \fifomem_mem_reg[3][1] (.clk (wclk), .d (wdata[1]), .sena
       (n_1580), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[3] [1]));
  CDN_flop \fifomem_mem_reg[3][2] (.clk (wclk), .d (wdata[2]), .sena
       (n_1580), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[3] [2]));
  CDN_flop \fifomem_mem_reg[3][3] (.clk (wclk), .d (wdata[3]), .sena
       (n_1580), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[3] [3]));
  CDN_flop \fifomem_mem_reg[3][4] (.clk (wclk), .d (wdata[4]), .sena
       (n_1580), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[3] [4]));
  CDN_flop \fifomem_mem_reg[3][5] (.clk (wclk), .d (wdata[5]), .sena
       (n_1580), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[3] [5]));
  CDN_flop \fifomem_mem_reg[3][6] (.clk (wclk), .d (wdata[6]), .sena
       (n_1580), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[3] [6]));
  CDN_flop \fifomem_mem_reg[3][7] (.clk (wclk), .d (wdata[7]), .sena
       (n_1580), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[3] [7]));
  CDN_flop \fifomem_mem_reg[4][0] (.clk (wclk), .d (wdata[0]), .sena
       (n_1583), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[4] [0]));
  CDN_flop \fifomem_mem_reg[4][1] (.clk (wclk), .d (wdata[1]), .sena
       (n_1583), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[4] [1]));
  CDN_flop \fifomem_mem_reg[4][2] (.clk (wclk), .d (wdata[2]), .sena
       (n_1583), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[4] [2]));
  CDN_flop \fifomem_mem_reg[4][3] (.clk (wclk), .d (wdata[3]), .sena
       (n_1583), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[4] [3]));
  CDN_flop \fifomem_mem_reg[4][4] (.clk (wclk), .d (wdata[4]), .sena
       (n_1583), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[4] [4]));
  CDN_flop \fifomem_mem_reg[4][5] (.clk (wclk), .d (wdata[5]), .sena
       (n_1583), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[4] [5]));
  CDN_flop \fifomem_mem_reg[4][6] (.clk (wclk), .d (wdata[6]), .sena
       (n_1583), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[4] [6]));
  CDN_flop \fifomem_mem_reg[4][7] (.clk (wclk), .d (wdata[7]), .sena
       (n_1583), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[4] [7]));
  CDN_flop \fifomem_mem_reg[5][0] (.clk (wclk), .d (wdata[0]), .sena
       (n_1585), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[5] [0]));
  CDN_flop \fifomem_mem_reg[5][1] (.clk (wclk), .d (wdata[1]), .sena
       (n_1585), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[5] [1]));
  CDN_flop \fifomem_mem_reg[5][2] (.clk (wclk), .d (wdata[2]), .sena
       (n_1585), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[5] [2]));
  CDN_flop \fifomem_mem_reg[5][3] (.clk (wclk), .d (wdata[3]), .sena
       (n_1585), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[5] [3]));
  CDN_flop \fifomem_mem_reg[5][4] (.clk (wclk), .d (wdata[4]), .sena
       (n_1585), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[5] [4]));
  CDN_flop \fifomem_mem_reg[5][5] (.clk (wclk), .d (wdata[5]), .sena
       (n_1585), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[5] [5]));
  CDN_flop \fifomem_mem_reg[5][6] (.clk (wclk), .d (wdata[6]), .sena
       (n_1585), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[5] [6]));
  CDN_flop \fifomem_mem_reg[5][7] (.clk (wclk), .d (wdata[7]), .sena
       (n_1585), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[5] [7]));
  CDN_flop \fifomem_mem_reg[6][0] (.clk (wclk), .d (wdata[0]), .sena
       (n_1584), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[6] [0]));
  CDN_flop \fifomem_mem_reg[6][1] (.clk (wclk), .d (wdata[1]), .sena
       (n_1584), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[6] [1]));
  CDN_flop \fifomem_mem_reg[6][2] (.clk (wclk), .d (wdata[2]), .sena
       (n_1584), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[6] [2]));
  CDN_flop \fifomem_mem_reg[6][3] (.clk (wclk), .d (wdata[3]), .sena
       (n_1584), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[6] [3]));
  CDN_flop \fifomem_mem_reg[6][4] (.clk (wclk), .d (wdata[4]), .sena
       (n_1584), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[6] [4]));
  CDN_flop \fifomem_mem_reg[6][5] (.clk (wclk), .d (wdata[5]), .sena
       (n_1584), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[6] [5]));
  CDN_flop \fifomem_mem_reg[6][6] (.clk (wclk), .d (wdata[6]), .sena
       (n_1584), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[6] [6]));
  CDN_flop \fifomem_mem_reg[6][7] (.clk (wclk), .d (wdata[7]), .sena
       (n_1584), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[6] [7]));
  CDN_flop \fifomem_mem_reg[7][0] (.clk (wclk), .d (wdata[0]), .sena
       (n_1568), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[7] [0]));
  CDN_flop \fifomem_mem_reg[7][1] (.clk (wclk), .d (wdata[1]), .sena
       (n_1568), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[7] [1]));
  CDN_flop \fifomem_mem_reg[7][2] (.clk (wclk), .d (wdata[2]), .sena
       (n_1568), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[7] [2]));
  CDN_flop \fifomem_mem_reg[7][3] (.clk (wclk), .d (wdata[3]), .sena
       (n_1568), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[7] [3]));
  CDN_flop \fifomem_mem_reg[7][4] (.clk (wclk), .d (wdata[4]), .sena
       (n_1568), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[7] [4]));
  CDN_flop \fifomem_mem_reg[7][5] (.clk (wclk), .d (wdata[5]), .sena
       (n_1568), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[7] [5]));
  CDN_flop \fifomem_mem_reg[7][6] (.clk (wclk), .d (wdata[6]), .sena
       (n_1568), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[7] [6]));
  CDN_flop \fifomem_mem_reg[7][7] (.clk (wclk), .d (wdata[7]), .sena
       (n_1568), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[7] [7]));
  CDN_flop \fifomem_mem_reg[8][0] (.clk (wclk), .d (wdata[0]), .sena
       (n_1581), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[8] [0]));
  CDN_flop \fifomem_mem_reg[8][1] (.clk (wclk), .d (wdata[1]), .sena
       (n_1581), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[8] [1]));
  CDN_flop \fifomem_mem_reg[8][2] (.clk (wclk), .d (wdata[2]), .sena
       (n_1581), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[8] [2]));
  CDN_flop \fifomem_mem_reg[8][3] (.clk (wclk), .d (wdata[3]), .sena
       (n_1581), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[8] [3]));
  CDN_flop \fifomem_mem_reg[8][4] (.clk (wclk), .d (wdata[4]), .sena
       (n_1581), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[8] [4]));
  CDN_flop \fifomem_mem_reg[8][5] (.clk (wclk), .d (wdata[5]), .sena
       (n_1581), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[8] [5]));
  CDN_flop \fifomem_mem_reg[8][6] (.clk (wclk), .d (wdata[6]), .sena
       (n_1581), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[8] [6]));
  CDN_flop \fifomem_mem_reg[8][7] (.clk (wclk), .d (wdata[7]), .sena
       (n_1581), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[8] [7]));
  CDN_flop \fifomem_mem_reg[9][0] (.clk (wclk), .d (wdata[0]), .sena
       (n_1575), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[9] [0]));
  CDN_flop \fifomem_mem_reg[9][1] (.clk (wclk), .d (wdata[1]), .sena
       (n_1575), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[9] [1]));
  CDN_flop \fifomem_mem_reg[9][2] (.clk (wclk), .d (wdata[2]), .sena
       (n_1575), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[9] [2]));
  CDN_flop \fifomem_mem_reg[9][3] (.clk (wclk), .d (wdata[3]), .sena
       (n_1575), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[9] [3]));
  CDN_flop \fifomem_mem_reg[9][4] (.clk (wclk), .d (wdata[4]), .sena
       (n_1575), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[9] [4]));
  CDN_flop \fifomem_mem_reg[9][5] (.clk (wclk), .d (wdata[5]), .sena
       (n_1575), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[9] [5]));
  CDN_flop \fifomem_mem_reg[9][6] (.clk (wclk), .d (wdata[6]), .sena
       (n_1575), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[9] [6]));
  CDN_flop \fifomem_mem_reg[9][7] (.clk (wclk), .d (wdata[7]), .sena
       (n_1575), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[9] [7]));
  CDN_flop \fifomem_mem_reg[10][0] (.clk (wclk), .d (wdata[0]), .sena
       (n_1577), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[10] [0]));
  CDN_flop \fifomem_mem_reg[10][1] (.clk (wclk), .d (wdata[1]), .sena
       (n_1577), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[10] [1]));
  CDN_flop \fifomem_mem_reg[10][2] (.clk (wclk), .d (wdata[2]), .sena
       (n_1577), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[10] [2]));
  CDN_flop \fifomem_mem_reg[10][3] (.clk (wclk), .d (wdata[3]), .sena
       (n_1577), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[10] [3]));
  CDN_flop \fifomem_mem_reg[10][4] (.clk (wclk), .d (wdata[4]), .sena
       (n_1577), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[10] [4]));
  CDN_flop \fifomem_mem_reg[10][5] (.clk (wclk), .d (wdata[5]), .sena
       (n_1577), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[10] [5]));
  CDN_flop \fifomem_mem_reg[10][6] (.clk (wclk), .d (wdata[6]), .sena
       (n_1577), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[10] [6]));
  CDN_flop \fifomem_mem_reg[10][7] (.clk (wclk), .d (wdata[7]), .sena
       (n_1577), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[10] [7]));
  CDN_flop \fifomem_mem_reg[11][0] (.clk (wclk), .d (wdata[0]), .sena
       (n_1576), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[11] [0]));
  CDN_flop \fifomem_mem_reg[11][1] (.clk (wclk), .d (wdata[1]), .sena
       (n_1576), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[11] [1]));
  CDN_flop \fifomem_mem_reg[11][2] (.clk (wclk), .d (wdata[2]), .sena
       (n_1576), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[11] [2]));
  CDN_flop \fifomem_mem_reg[11][3] (.clk (wclk), .d (wdata[3]), .sena
       (n_1576), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[11] [3]));
  CDN_flop \fifomem_mem_reg[11][4] (.clk (wclk), .d (wdata[4]), .sena
       (n_1576), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[11] [4]));
  CDN_flop \fifomem_mem_reg[11][5] (.clk (wclk), .d (wdata[5]), .sena
       (n_1576), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[11] [5]));
  CDN_flop \fifomem_mem_reg[11][6] (.clk (wclk), .d (wdata[6]), .sena
       (n_1576), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[11] [6]));
  CDN_flop \fifomem_mem_reg[11][7] (.clk (wclk), .d (wdata[7]), .sena
       (n_1576), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[11] [7]));
  CDN_flop \fifomem_mem_reg[12][0] (.clk (wclk), .d (wdata[0]), .sena
       (n_1586), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[12] [0]));
  CDN_flop \fifomem_mem_reg[12][1] (.clk (wclk), .d (wdata[1]), .sena
       (n_1586), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[12] [1]));
  CDN_flop \fifomem_mem_reg[12][2] (.clk (wclk), .d (wdata[2]), .sena
       (n_1586), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[12] [2]));
  CDN_flop \fifomem_mem_reg[12][3] (.clk (wclk), .d (wdata[3]), .sena
       (n_1586), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[12] [3]));
  CDN_flop \fifomem_mem_reg[12][4] (.clk (wclk), .d (wdata[4]), .sena
       (n_1586), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[12] [4]));
  CDN_flop \fifomem_mem_reg[12][5] (.clk (wclk), .d (wdata[5]), .sena
       (n_1586), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[12] [5]));
  CDN_flop \fifomem_mem_reg[12][6] (.clk (wclk), .d (wdata[6]), .sena
       (n_1586), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[12] [6]));
  CDN_flop \fifomem_mem_reg[12][7] (.clk (wclk), .d (wdata[7]), .sena
       (n_1586), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[12] [7]));
  CDN_flop \fifomem_mem_reg[13][0] (.clk (wclk), .d (wdata[0]), .sena
       (n_1588), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[13] [0]));
  CDN_flop \fifomem_mem_reg[13][1] (.clk (wclk), .d (wdata[1]), .sena
       (n_1588), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[13] [1]));
  CDN_flop \fifomem_mem_reg[13][2] (.clk (wclk), .d (wdata[2]), .sena
       (n_1588), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[13] [2]));
  CDN_flop \fifomem_mem_reg[13][3] (.clk (wclk), .d (wdata[3]), .sena
       (n_1588), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[13] [3]));
  CDN_flop \fifomem_mem_reg[13][4] (.clk (wclk), .d (wdata[4]), .sena
       (n_1588), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[13] [4]));
  CDN_flop \fifomem_mem_reg[13][5] (.clk (wclk), .d (wdata[5]), .sena
       (n_1588), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[13] [5]));
  CDN_flop \fifomem_mem_reg[13][6] (.clk (wclk), .d (wdata[6]), .sena
       (n_1588), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[13] [6]));
  CDN_flop \fifomem_mem_reg[13][7] (.clk (wclk), .d (wdata[7]), .sena
       (n_1588), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[13] [7]));
  CDN_flop \fifomem_mem_reg[14][0] (.clk (wclk), .d (wdata[0]), .sena
       (n_1587), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[14] [0]));
  CDN_flop \fifomem_mem_reg[14][1] (.clk (wclk), .d (wdata[1]), .sena
       (n_1587), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[14] [1]));
  CDN_flop \fifomem_mem_reg[14][2] (.clk (wclk), .d (wdata[2]), .sena
       (n_1587), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[14] [2]));
  CDN_flop \fifomem_mem_reg[14][3] (.clk (wclk), .d (wdata[3]), .sena
       (n_1587), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[14] [3]));
  CDN_flop \fifomem_mem_reg[14][4] (.clk (wclk), .d (wdata[4]), .sena
       (n_1587), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[14] [4]));
  CDN_flop \fifomem_mem_reg[14][5] (.clk (wclk), .d (wdata[5]), .sena
       (n_1587), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[14] [5]));
  CDN_flop \fifomem_mem_reg[14][6] (.clk (wclk), .d (wdata[6]), .sena
       (n_1587), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[14] [6]));
  CDN_flop \fifomem_mem_reg[14][7] (.clk (wclk), .d (wdata[7]), .sena
       (n_1587), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[14] [7]));
  CDN_flop \fifomem_mem_reg[15][0] (.clk (wclk), .d (wdata[0]), .sena
       (n_1567), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[15] [0]));
  CDN_flop \fifomem_mem_reg[15][1] (.clk (wclk), .d (wdata[1]), .sena
       (n_1567), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[15] [1]));
  CDN_flop \fifomem_mem_reg[15][2] (.clk (wclk), .d (wdata[2]), .sena
       (n_1567), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[15] [2]));
  CDN_flop \fifomem_mem_reg[15][3] (.clk (wclk), .d (wdata[3]), .sena
       (n_1567), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[15] [3]));
  CDN_flop \fifomem_mem_reg[15][4] (.clk (wclk), .d (wdata[4]), .sena
       (n_1567), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[15] [4]));
  CDN_flop \fifomem_mem_reg[15][5] (.clk (wclk), .d (wdata[5]), .sena
       (n_1567), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[15] [5]));
  CDN_flop \fifomem_mem_reg[15][6] (.clk (wclk), .d (wdata[6]), .sena
       (n_1567), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[15] [6]));
  CDN_flop \fifomem_mem_reg[15][7] (.clk (wclk), .d (wdata[7]), .sena
       (n_1567), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\fifomem_mem[15] [7]));
  or g885 (n_605, wc, wfull);
  not gc (wc, winc);
  or g888 (n_606, n_605, wc0);
  not gc0 (wc0, waddr[0]);
  nand g1192 (n_597, raddr[1], raddr[2]);
  or g1217 (n_676, n_589, n_597);
  or g1224 (n_675, wc1, rempty);
  not gc1 (wc1, rinc);
  or g1243 (n_589, wc2, n_675);
  not gc2 (wc2, raddr[0]);
  or g1521 (n_621, n_1458, n_1459);
  or g1552 (n_623, n_1508, n_1509);
  or g1597 (n_1508, n_1518, n_1519);
  or g1598 (n_1458, n_1468, n_1469);
  or g1599 (n_1469, n_1466, n_1467);
  or g1600 (n_1519, n_1516, n_1517);
  nand g1601 (n_1468, n_1464, n_1465);
  nand g1602 (n_1543, n_620, wq2_rptr[3]);
  or g1603 (n_1544, n_620, wq2_rptr[3]);
  nand g1604 (n_1509, n_1543, n_1544);
  nand g1605 (n_1467, n_1462, n_1463);
  nand g1606 (n_1517, n_1512, n_1513);
  or g1607 (n_1545, wc3, n_616);
  not gc3 (wc3, n_619);
  or g1608 (n_1546, n_619, wc4);
  not gc4 (wc4, n_616);
  nand g1609 (n_620, n_1545, n_1546);
  or g1610 (n_1547, wc5, n_619);
  not gc5 (wc5, wq2_rptr[4]);
  or g1611 (n_1548, wq2_rptr[4], wc6);
  not gc6 (wc6, n_619);
  nand g1612 (n_678, n_1547, n_1548);
  or g1613 (n_1464, wc7, n_599);
  not gc7 (wc7, rq2_wptr[2]);
  or g1614 (rdata[2], n_1232, n_1233);
  or g1615 (n_1465, rq2_wptr[2], wc8);
  not gc8 (wc8, n_599);
  or g1616 (rdata[1], n_1322, n_1323);
  or g1617 (rdata[4], n_1052, n_1053);
  or g1618 (rdata[3], n_1142, n_1143);
  nand g1619 (n_1516, n_1510, n_1511);
  or g1620 (n_1512, wc9, n_617);
  not gc9 (wc9, wq2_rptr[2]);
  or g1621 (n_1462, wc10, n_596);
  not gc10 (wc10, rq2_wptr[1]);
  or g1622 (n_1463, rq2_wptr[1], wc11);
  not gc11 (wc11, n_596);
  or g1623 (n_1513, wq2_rptr[2], wc12);
  not gc12 (wc12, n_617);
  or g1624 (rdata[6], n_872, n_873);
  or g1625 (rdata[7], n_782, n_783);
  or g1626 (rdata[5], n_962, n_963);
  nand g1627 (n_1518, n_1514, n_1515);
  or g1628 (rdata[0], n_1412, n_1413);
  or g1629 (n_782, n_778, n_779);
  or g1630 (n_783, n_780, n_781);
  nand g1631 (n_1466, n_1460, n_1461);
  or g1632 (n_872, n_868, n_869);
  or g1633 (n_963, n_960, n_961);
  or g1634 (n_1233, n_1230, n_1231);
  or g1635 (n_1232, n_1228, n_1229);
  or g1636 (n_1549, wc13, n_595);
  not gc13 (wc13, n_598);
  or g1637 (n_1550, n_598, wc14);
  not gc14 (wc14, n_595);
  nand g1638 (n_599, n_1549, n_1550);
  or g1639 (n_1053, n_1050, n_1051);
  or g1640 (n_1551, wc15, rq2_wptr[3]);
  not gc15 (wc15, n_602);
  or g1641 (n_1552, n_602, wc16);
  not gc16 (wc16, rq2_wptr[3]);
  nand g1642 (n_1459, n_1551, n_1552);
  or g1643 (n_873, n_870, n_871);
  or g1644 (n_1553, wc17, n_590);
  not gc17 (wc17, n_595);
  or g1645 (n_1554, n_595, wc18);
  not gc18 (wc18, n_590);
  nand g1646 (n_596, n_1553, n_1554);
  or g1647 (n_1052, n_1048, n_1049);
  or g1648 (n_1514, wc19, n_614);
  not gc19 (wc19, wq2_rptr[1]);
  or g1649 (n_1143, n_1140, n_1141);
  or g1650 (n_1555, wc20, n_613);
  not gc20 (wc20, n_616);
  or g1651 (n_1556, n_616, wc21);
  not gc21 (wc21, n_613);
  nand g1652 (n_617, n_1555, n_1556);
  or g1653 (n_1142, n_1138, n_1139);
  nand g1654 (n_1557, wptr[4], n_618);
  or g1655 (n_1558, wptr[4], n_618);
  nand g1656 (n_619, n_1557, n_1558);
  or g1657 (n_1515, wc22, n_611);
  not gc22 (wc22, wq2_rptr[0]);
  or g1658 (n_1510, wq2_rptr[0], wc23);
  not gc23 (wc23, n_611);
  or g1659 (n_1511, wq2_rptr[1], wc24);
  not gc24 (wc24, n_614);
  or g1660 (n_962, n_958, n_959);
  or g1661 (n_1323, n_1320, n_1321);
  or g1662 (n_1322, n_1318, n_1319);
  or g1663 (n_1412, n_1408, n_1409);
  or g1664 (n_1413, n_1410, n_1411);
  or g1665 (n_868, n_860, n_861);
  or g1666 (n_869, n_862, n_863);
  or g1667 (n_870, n_864, n_865);
  nand g1668 (n_1559, rq2_wptr[4], n_601);
  or g1669 (n_1560, rq2_wptr[4], n_601);
  nand g1670 (n_677, n_1559, n_1560);
  or g1671 (n_1231, n_1226, n_1227);
  or g1672 (n_1230, n_1224, n_1225);
  or g1673 (n_1229, n_1222, n_1223);
  or g1674 (n_1228, n_1220, n_1221);
  or g1675 (n_1411, n_1406, n_1407);
  or g1676 (n_1561, wc25, n_610);
  not gc25 (wc25, n_608);
  or g1677 (n_1562, n_608, wc26);
  not gc26 (wc26, n_610);
  nand g1678 (n_611, n_1561, n_1562);
  or g1679 (n_1410, n_1404, n_1405);
  or g1680 (n_1563, wc27, n_608);
  not gc27 (wc27, n_613);
  or g1681 (n_1564, n_613, wc28);
  not gc28 (wc28, n_608);
  nand g1682 (n_614, n_1563, n_1564);
  or g1683 (n_961, n_956, n_957);
  nand g1684 (n_1565, n_615, waddr[3]);
  or g1685 (n_1566, n_615, waddr[3]);
  nand g1686 (n_616, n_1565, n_1566);
  or g1687 (n_618, wc29, n_615);
  not gc29 (wc29, waddr[3]);
  not g1688 (n_1567, n_618);
  or g1691 (n_960, n_954, n_955);
  or g1692 (n_959, n_952, n_953);
  or g1693 (n_1051, n_1046, n_1047);
  or g1694 (n_1321, n_1316, n_1317);
  or g1695 (n_1320, n_1314, n_1315);
  or g1696 (n_1319, n_1312, n_1313);
  or g1697 (n_1318, n_1310, n_1311);
  or g1698 (n_1050, n_1044, n_1045);
  or g1699 (n_1049, n_1042, n_1043);
  or g1700 (n_1048, n_1040, n_1041);
  or g1701 (n_1460, wc30, n_592);
  not gc30 (wc30, rq2_wptr[0]);
  or g1702 (n_1461, rq2_wptr[0], wc31);
  not gc31 (wc31, n_592);
  or g1703 (n_1408, n_1400, n_1401);
  or g1704 (n_1409, n_1402, n_1403);
  or g1705 (n_871, n_866, n_867);
  or g1706 (n_1569, wc32, n_598);
  not gc32 (wc32, n_601);
  or g1707 (n_1570, n_601, wc33);
  not gc33 (wc33, n_598);
  nand g1708 (n_602, n_1569, n_1570);
  or g1709 (n_1141, n_1136, n_1137);
  or g1710 (n_1140, n_1134, n_1135);
  or g1711 (n_1139, n_1132, n_1133);
  or g1712 (n_1138, n_1130, n_1131);
  or g1713 (n_595, wc34, n_693);
  not gc34 (wc34, n_692);
  or g1714 (n_958, n_950, n_951);
  or g1715 (n_778, n_770, n_771);
  or g1716 (n_779, n_772, n_773);
  or g1717 (n_780, n_774, n_775);
  or g1718 (n_781, n_776, n_777);
  nand g1719 (n_1405, n_1396, n_1397);
  nand g1720 (n_1404, n_1394, n_1395);
  nand g1721 (n_1401, n_1392, n_1393);
  nand g1722 (n_1406, n_1390, n_1391);
  nand g1723 (n_1403, n_1388, n_1389);
  nand g1724 (n_1402, n_1386, n_1387);
  nand g1725 (n_1400, n_1384, n_1385);
  nand g1726 (n_1571, n_676, raddr[3]);
  or g1727 (n_1572, n_676, raddr[3]);
  nand g1728 (n_598, n_1571, n_1572);
  nand g1729 (n_608, n_607, n_1419);
  or g1730 (n_1573, n_612, waddr[2]);
  nand g1731 (n_1574, n_612, waddr[2]);
  nand g1732 (n_613, n_1573, n_1574);
  or g1733 (n_615, n_612, wc35);
  not gc35 (wc35, waddr[2]);
  nand g1740 (n_1317, n_1308, n_1309);
  nand g1741 (n_1315, n_1306, n_1307);
  nand g1742 (n_1314, n_1304, n_1305);
  nand g1743 (n_1311, n_1302, n_1303);
  nand g1744 (n_1316, n_1300, n_1301);
  nand g1745 (n_1313, n_1298, n_1299);
  nand g1746 (n_1312, n_1296, n_1297);
  nand g1747 (n_1310, n_1294, n_1295);
  nand g1764 (n_693, n_593, n_691);
  or g1771 (n_1589, wc36, n_591);
  not gc36 (wc36, n_590);
  or g1772 (n_1590, n_590, wc37);
  not gc37 (wc37, n_591);
  nand g1773 (n_592, n_1589, n_1590);
  nand g1774 (n_1227, n_1218, n_1219);
  nand g1775 (n_1225, n_1216, n_1217);
  nand g1776 (n_1224, n_1214, n_1215);
  nand g1777 (n_1221, n_1212, n_1213);
  nand g1778 (n_1226, n_1210, n_1211);
  nand g1779 (n_1223, n_1208, n_1209);
  nand g1780 (n_1222, n_1206, n_1207);
  nand g1781 (n_867, n_858, n_859);
  nand g1782 (n_1407, n_1398, n_1399);
  nand g1783 (n_1137, n_1128, n_1129);
  nand g1784 (n_1135, n_1126, n_1127);
  nand g1785 (n_1134, n_1124, n_1125);
  nand g1786 (n_1131, n_1122, n_1123);
  nand g1787 (n_1136, n_1120, n_1121);
  nand g1788 (n_1133, n_1118, n_1119);
  nand g1789 (n_1132, n_1116, n_1117);
  nand g1790 (n_1130, n_1114, n_1115);
  nand g1791 (n_1591, n_600, rptr[4]);
  or g1792 (n_1592, n_600, rptr[4]);
  nand g1793 (n_601, n_1591, n_1592);
  nand g1794 (n_770, n_754, n_755);
  nand g1795 (n_772, n_756, n_757);
  nand g1796 (n_773, n_758, n_759);
  nand g1797 (n_1047, n_1038, n_1039);
  nand g1798 (n_1045, n_1036, n_1037);
  nand g1799 (n_1044, n_1034, n_1035);
  nand g1800 (n_1041, n_1032, n_1033);
  nand g1801 (n_1046, n_1030, n_1031);
  nand g1802 (n_1043, n_1028, n_1029);
  nand g1803 (n_1042, n_1026, n_1027);
  nand g1804 (n_1040, n_1024, n_1025);
  nand g1805 (n_776, n_760, n_761);
  nand g1806 (n_771, n_762, n_763);
  nand g1807 (n_774, n_764, n_765);
  nand g1808 (n_775, n_766, n_767);
  nand g1809 (n_777, n_768, n_769);
  nand g1810 (n_860, n_844, n_845);
  nand g1811 (n_862, n_846, n_847);
  nand g1812 (n_863, n_848, n_849);
  nand g1813 (n_866, n_850, n_851);
  nand g1814 (n_957, n_948, n_949);
  nand g1815 (n_955, n_946, n_947);
  nand g1816 (n_954, n_944, n_945);
  nand g1817 (n_951, n_942, n_943);
  nand g1818 (n_956, n_940, n_941);
  nand g1819 (n_953, n_938, n_939);
  nand g1820 (n_952, n_936, n_937);
  nand g1821 (n_950, n_934, n_935);
  nand g1822 (n_861, n_852, n_853);
  nand g1823 (n_864, n_854, n_855);
  nand g1824 (n_865, n_856, n_857);
  nand g1825 (n_1220, n_1204, n_1205);
  or g1826 (n_937, wc38, n_647);
  not gc38 (wc38, \fifomem_mem[3] [5]);
  or g1827 (n_936, wc39, n_653);
  not gc39 (wc39, \fifomem_mem[2] [5]);
  or g1828 (n_935, wc40, n_659);
  not gc40 (wc40, \fifomem_mem[1] [5]);
  or g1829 (n_934, wc41, n_662);
  not gc41 (wc41, \fifomem_mem[0] [5]);
  or g1830 (n_938, wc42, n_654);
  not gc42 (wc42, \fifomem_mem[4] [5]);
  or g1831 (n_939, wc43, n_648);
  not gc43 (wc43, \fifomem_mem[5] [5]);
  or g1832 (n_940, wc44, n_666);
  not gc44 (wc44, \fifomem_mem[6] [5]);
  or g1833 (n_941, wc45, n_664);
  not gc45 (wc45, \fifomem_mem[7] [5]);
  or g1834 (n_942, wc46, n_660);
  not gc46 (wc46, \fifomem_mem[8] [5]);
  or g1835 (n_943, wc47, n_661);
  not gc47 (wc47, \fifomem_mem[9] [5]);
  or g1836 (n_944, wc48, n_650);
  not gc48 (wc48, \fifomem_mem[10] [5]);
  or g1837 (n_945, wc49, n_656);
  not gc49 (wc49, \fifomem_mem[11] [5]);
  or g1838 (n_946, wc50, n_651);
  not gc50 (wc50, \fifomem_mem[12] [5]);
  or g1839 (n_947, wc51, n_657);
  not gc51 (wc51, \fifomem_mem[13] [5]);
  or g1840 (n_948, wc52, n_665);
  not gc52 (wc52, \fifomem_mem[14] [5]);
  or g1841 (n_600, n_684, n_589);
  or g1842 (n_1024, wc53, n_662);
  not gc53 (wc53, \fifomem_mem[0] [4]);
  or g1843 (n_1025, wc54, n_659);
  not gc54 (wc54, \fifomem_mem[1] [4]);
  or g1844 (n_1026, wc55, n_653);
  not gc55 (wc55, \fifomem_mem[2] [4]);
  or g1845 (n_859, wc56, n_663);
  not gc56 (wc56, \fifomem_mem[15] [6]);
  or g1846 (n_858, wc57, n_665);
  not gc57 (wc57, \fifomem_mem[14] [6]);
  or g1847 (n_857, wc58, n_657);
  not gc58 (wc58, \fifomem_mem[13] [6]);
  or g1848 (n_856, wc59, n_651);
  not gc59 (wc59, \fifomem_mem[12] [6]);
  or g1849 (n_855, wc60, n_656);
  not gc60 (wc60, \fifomem_mem[11] [6]);
  or g1850 (n_854, wc61, n_650);
  not gc61 (wc61, \fifomem_mem[10] [6]);
  or g1851 (n_853, wc62, n_661);
  not gc62 (wc62, \fifomem_mem[9] [6]);
  or g1852 (n_852, wc63, n_660);
  not gc63 (wc63, \fifomem_mem[8] [6]);
  or g1853 (n_851, wc64, n_664);
  not gc64 (wc64, \fifomem_mem[7] [6]);
  or g1854 (n_850, wc65, n_666);
  not gc65 (wc65, \fifomem_mem[6] [6]);
  or g1855 (n_849, wc66, n_648);
  not gc66 (wc66, \fifomem_mem[5] [6]);
  or g1856 (n_848, wc67, n_654);
  not gc67 (wc67, \fifomem_mem[4] [6]);
  or g1857 (n_847, wc68, n_647);
  not gc68 (wc68, \fifomem_mem[3] [6]);
  or g1858 (n_846, wc69, n_653);
  not gc69 (wc69, \fifomem_mem[2] [6]);
  or g1859 (n_845, wc70, n_659);
  not gc70 (wc70, \fifomem_mem[1] [6]);
  or g1860 (n_844, wc71, n_662);
  not gc71 (wc71, \fifomem_mem[0] [6]);
  or g1861 (n_1027, wc72, n_647);
  not gc72 (wc72, \fifomem_mem[3] [4]);
  or g1862 (n_1028, wc73, n_654);
  not gc73 (wc73, \fifomem_mem[4] [4]);
  or g1863 (n_1029, wc74, n_648);
  not gc74 (wc74, \fifomem_mem[5] [4]);
  or g1864 (n_1030, wc75, n_666);
  not gc75 (wc75, \fifomem_mem[6] [4]);
  or g1865 (n_1031, wc76, n_664);
  not gc76 (wc76, \fifomem_mem[7] [4]);
  or g1866 (n_1032, wc77, n_660);
  not gc77 (wc77, \fifomem_mem[8] [4]);
  or g1867 (n_1033, wc78, n_661);
  not gc78 (wc78, \fifomem_mem[9] [4]);
  or g1868 (n_1034, wc79, n_650);
  not gc79 (wc79, \fifomem_mem[10] [4]);
  or g1869 (n_1035, wc80, n_656);
  not gc80 (wc80, \fifomem_mem[11] [4]);
  or g1870 (n_1036, wc81, n_651);
  not gc81 (wc81, \fifomem_mem[12] [4]);
  or g1871 (n_1037, wc82, n_657);
  not gc82 (wc82, \fifomem_mem[13] [4]);
  or g1872 (n_1038, wc83, n_665);
  not gc83 (wc83, \fifomem_mem[14] [4]);
  or g1873 (n_1039, wc84, n_663);
  not gc84 (wc84, \fifomem_mem[15] [4]);
  or g1874 (n_1114, wc85, n_662);
  not gc85 (wc85, \fifomem_mem[0] [3]);
  or g1875 (n_1115, wc86, n_659);
  not gc86 (wc86, \fifomem_mem[1] [3]);
  or g1876 (n_769, wc87, n_663);
  not gc87 (wc87, \fifomem_mem[15] [7]);
  or g1877 (n_768, wc88, n_665);
  not gc88 (wc88, \fifomem_mem[14] [7]);
  or g1878 (n_767, wc89, n_657);
  not gc89 (wc89, \fifomem_mem[13] [7]);
  or g1879 (n_766, wc90, n_651);
  not gc90 (wc90, \fifomem_mem[12] [7]);
  or g1880 (n_765, wc91, n_656);
  not gc91 (wc91, \fifomem_mem[11] [7]);
  or g1881 (n_764, wc92, n_650);
  not gc92 (wc92, \fifomem_mem[10] [7]);
  or g1882 (n_763, wc93, n_661);
  not gc93 (wc93, \fifomem_mem[9] [7]);
  or g1883 (n_762, wc94, n_660);
  not gc94 (wc94, \fifomem_mem[8] [7]);
  or g1884 (n_761, wc95, n_664);
  not gc95 (wc95, \fifomem_mem[7] [7]);
  or g1885 (n_760, wc96, n_666);
  not gc96 (wc96, \fifomem_mem[6] [7]);
  or g1886 (n_759, wc97, n_648);
  not gc97 (wc97, \fifomem_mem[5] [7]);
  or g1887 (n_758, wc98, n_654);
  not gc98 (wc98, \fifomem_mem[4] [7]);
  or g1888 (n_757, wc99, n_647);
  not gc99 (wc99, \fifomem_mem[3] [7]);
  or g1889 (n_756, wc100, n_653);
  not gc100 (wc100, \fifomem_mem[2] [7]);
  or g1890 (n_755, wc101, n_659);
  not gc101 (wc101, \fifomem_mem[1] [7]);
  or g1891 (n_754, wc102, n_662);
  not gc102 (wc102, \fifomem_mem[0] [7]);
  or g1892 (n_1116, wc103, n_653);
  not gc103 (wc103, \fifomem_mem[2] [3]);
  or g1893 (n_1117, wc104, n_647);
  not gc104 (wc104, \fifomem_mem[3] [3]);
  or g1894 (n_1118, wc105, n_654);
  not gc105 (wc105, \fifomem_mem[4] [3]);
  or g1895 (n_1119, wc106, n_648);
  not gc106 (wc106, \fifomem_mem[5] [3]);
  or g1896 (n_1120, wc107, n_666);
  not gc107 (wc107, \fifomem_mem[6] [3]);
  or g1897 (n_1121, wc108, n_664);
  not gc108 (wc108, \fifomem_mem[7] [3]);
  or g1898 (n_1122, wc109, n_660);
  not gc109 (wc109, \fifomem_mem[8] [3]);
  or g1899 (n_1123, wc110, n_661);
  not gc110 (wc110, \fifomem_mem[9] [3]);
  or g1900 (n_1124, wc111, n_650);
  not gc111 (wc111, \fifomem_mem[10] [3]);
  or g1901 (n_1125, wc112, n_656);
  not gc112 (wc112, \fifomem_mem[11] [3]);
  or g1902 (n_1126, wc113, n_651);
  not gc113 (wc113, \fifomem_mem[12] [3]);
  or g1903 (n_1127, wc114, n_657);
  not gc114 (wc114, \fifomem_mem[13] [3]);
  or g1904 (n_1128, wc115, n_665);
  not gc115 (wc115, \fifomem_mem[14] [3]);
  or g1905 (n_1129, wc116, n_663);
  not gc116 (wc116, \fifomem_mem[15] [3]);
  or g1906 (n_1204, wc117, n_662);
  not gc117 (wc117, \fifomem_mem[0] [2]);
  or g1907 (n_1205, wc118, n_659);
  not gc118 (wc118, \fifomem_mem[1] [2]);
  or g1908 (n_1206, wc119, n_653);
  not gc119 (wc119, \fifomem_mem[2] [2]);
  or g1909 (n_1207, wc120, n_647);
  not gc120 (wc120, \fifomem_mem[3] [2]);
  or g1910 (n_1208, wc121, n_654);
  not gc121 (wc121, \fifomem_mem[4] [2]);
  or g1911 (n_1209, wc122, n_648);
  not gc122 (wc122, \fifomem_mem[5] [2]);
  or g1912 (n_1210, wc123, n_666);
  not gc123 (wc123, \fifomem_mem[6] [2]);
  or g1913 (n_1211, wc124, n_664);
  not gc124 (wc124, \fifomem_mem[7] [2]);
  or g1914 (n_1212, wc125, n_660);
  not gc125 (wc125, \fifomem_mem[8] [2]);
  or g1915 (n_1213, wc126, n_661);
  not gc126 (wc126, \fifomem_mem[9] [2]);
  or g1916 (n_1214, wc127, n_650);
  not gc127 (wc127, \fifomem_mem[10] [2]);
  or g1917 (n_1215, wc128, n_656);
  not gc128 (wc128, \fifomem_mem[11] [2]);
  or g1918 (n_1216, wc129, n_651);
  not gc129 (wc129, \fifomem_mem[12] [2]);
  or g1919 (n_1217, wc130, n_657);
  not gc130 (wc130, \fifomem_mem[13] [2]);
  or g1920 (n_1218, wc131, n_665);
  not gc131 (wc131, \fifomem_mem[14] [2]);
  or g1921 (n_1219, wc132, n_663);
  not gc132 (wc132, \fifomem_mem[15] [2]);
  or g1922 (n_1388, wc133, n_654);
  not gc133 (wc133, \fifomem_mem[4] [0]);
  or g1923 (n_1389, wc134, n_648);
  not gc134 (wc134, \fifomem_mem[5] [0]);
  or g1924 (n_1390, wc135, n_666);
  not gc135 (wc135, \fifomem_mem[6] [0]);
  or g1925 (n_1391, wc136, n_664);
  not gc136 (wc136, \fifomem_mem[7] [0]);
  or g1926 (n_1392, wc137, n_660);
  not gc137 (wc137, \fifomem_mem[8] [0]);
  or g1927 (n_1393, wc138, n_661);
  not gc138 (wc138, \fifomem_mem[9] [0]);
  or g1928 (n_1394, wc139, n_650);
  not gc139 (wc139, \fifomem_mem[10] [0]);
  or g1929 (n_612, wc140, n_606);
  not gc140 (wc140, waddr[1]);
  nand g1930 (n_1593, n_589, raddr[1]);
  or g1931 (n_1594, n_589, raddr[1]);
  nand g1932 (n_590, n_1593, n_1594);
  or g1933 (n_1395, wc141, n_656);
  not gc141 (wc141, \fifomem_mem[11] [0]);
  nand g1934 (n_610, n_609, n_1416);
  or g1935 (n_1398, wc142, n_665);
  not gc142 (wc142, \fifomem_mem[14] [0]);
  or g1936 (n_949, wc143, n_663);
  not gc143 (wc143, \fifomem_mem[15] [5]);
  or g1937 (n_1396, wc144, n_651);
  not gc144 (wc144, \fifomem_mem[12] [0]);
  or g1938 (n_1294, wc145, n_662);
  not gc145 (wc145, \fifomem_mem[0] [1]);
  nand g1939 (n_1419, waddr[1], n_606);
  or g1940 (n_607, n_606, waddr[1]);
  nand g1941 (n_692, raddr[2], n_589);
  or g1942 (n_1399, wc146, n_663);
  not gc146 (wc146, \fifomem_mem[15] [0]);
  or g1943 (n_1397, wc147, n_657);
  not gc147 (wc147, \fifomem_mem[13] [0]);
  or g1944 (n_691, n_594, n_589);
  or g1945 (n_1295, wc148, n_659);
  not gc148 (wc148, \fifomem_mem[1] [1]);
  or g1946 (n_1296, wc149, n_653);
  not gc149 (wc149, \fifomem_mem[2] [1]);
  or g1947 (n_1297, wc150, n_647);
  not gc150 (wc150, \fifomem_mem[3] [1]);
  or g1948 (n_1298, wc151, n_654);
  not gc151 (wc151, \fifomem_mem[4] [1]);
  or g1949 (n_1299, wc152, n_648);
  not gc152 (wc152, \fifomem_mem[5] [1]);
  or g1950 (n_1300, wc153, n_666);
  not gc153 (wc153, \fifomem_mem[6] [1]);
  or g1951 (n_1301, wc154, n_664);
  not gc154 (wc154, \fifomem_mem[7] [1]);
  or g1952 (n_1302, wc155, n_660);
  not gc155 (wc155, \fifomem_mem[8] [1]);
  or g1953 (n_1303, wc156, n_661);
  not gc156 (wc156, \fifomem_mem[9] [1]);
  or g1954 (n_1304, wc157, n_650);
  not gc157 (wc157, \fifomem_mem[10] [1]);
  or g1955 (n_635, waddr[1], n_609);
  or g1956 (n_1305, wc158, n_656);
  not gc158 (wc158, \fifomem_mem[11] [1]);
  or g1957 (n_1306, wc159, n_651);
  not gc159 (wc159, \fifomem_mem[12] [1]);
  or g1958 (n_1307, wc160, n_657);
  not gc160 (wc160, \fifomem_mem[13] [1]);
  or g1959 (n_1308, wc161, n_665);
  not gc161 (wc161, \fifomem_mem[14] [1]);
  or g1960 (n_1309, wc162, n_663);
  not gc162 (wc162, \fifomem_mem[15] [1]);
  or g1961 (n_629, wc163, n_609);
  not gc163 (wc163, waddr[1]);
  or g1962 (n_1384, wc164, n_662);
  not gc164 (wc164, \fifomem_mem[0] [0]);
  or g1963 (n_1385, wc165, n_659);
  not gc165 (wc165, \fifomem_mem[1] [0]);
  or g1964 (n_1386, wc166, n_653);
  not gc166 (wc166, \fifomem_mem[2] [0]);
  or g1965 (n_1387, wc167, n_647);
  not gc167 (wc167, \fifomem_mem[3] [0]);
  or g1966 (n_666, n_597, n_652);
  or g1967 (n_665, n_597, n_649);
  or g1968 (n_664, n_597, n_646);
  or g1969 (n_663, n_597, n_655);
  or g1970 (n_662, n_658, n_652);
  or g1971 (n_661, n_658, n_655);
  or g1972 (n_660, n_658, n_649);
  or g1973 (n_659, n_658, n_646);
  or g1974 (n_657, n_655, n_593);
  or g1975 (n_656, n_655, n_594);
  or g1976 (n_654, n_652, n_593);
  or g1977 (n_653, n_652, n_594);
  or g1978 (n_651, n_649, n_593);
  or g1979 (n_650, n_649, n_594);
  or g1980 (n_648, n_646, n_593);
  or g1981 (n_647, n_646, n_594);
  nand g1982 (n_1416, waddr[0], n_605);
  or g1983 (n_609, n_605, waddr[0]);
  or g1984 (n_684, wc168, n_597);
  not gc168 (wc168, raddr[3]);
  nand g1985 (n_1595, n_675, raddr[0]);
  or g1986 (n_1596, n_675, raddr[0]);
  nand g1987 (n_591, n_1595, n_1596);
  or g1988 (n_626, waddr[2], wc169);
  not gc169 (wc169, waddr[3]);
  or g1989 (n_631, waddr[2], waddr[3]);
  or g1990 (n_638, wc170, waddr[3]);
  not gc170 (wc170, waddr[2]);
  nand g1991 (n_642, waddr[2], waddr[3]);
  or g1992 (n_594, wc171, raddr[2]);
  not gc171 (wc171, raddr[1]);
  or g1993 (n_593, raddr[1], wc172);
  not gc172 (wc172, raddr[2]);
  or g1994 (n_646, wc173, raddr[3]);
  not gc173 (wc173, raddr[0]);
  or g1995 (n_649, raddr[0], wc174);
  not gc174 (wc174, raddr[3]);
  or g1996 (n_652, raddr[0], raddr[3]);
  nand g1997 (n_655, raddr[0], raddr[3]);
  or g1998 (n_658, raddr[1], raddr[2]);
  nor g1999 (n_1575, n_626, n_607);
  nor g2000 (n_1576, n_626, n_612);
  nor g2001 (n_1577, n_629, n_626);
  nor g2002 (n_1578, n_631, n_629);
  nor g2003 (n_1579, n_631, n_607);
  nor g2004 (n_1580, n_631, n_612);
  nor g2005 (n_1581, n_635, n_626);
  nor g2006 (n_1582, n_635, n_631);
  nor g2007 (n_1583, n_638, n_635);
  nor g2008 (n_1584, n_638, n_629);
  nor g2009 (n_1585, n_638, n_607);
  nor g2010 (n_1586, n_642, n_635);
  nor g2011 (n_1587, n_642, n_629);
  nor g2012 (n_1588, n_642, n_607);
  and g2014 (n_1542, n_677, wc175);
  not gc175 (wc175, n_621);
  and g2015 (n_1541, n_678, wc176);
  not gc176 (wc176, n_623);
  not g2016 (n_1568, n_1566);
  CDN_flop \rptr_empty_rbin_reg[0] (.clk (rclk), .d (n_591), .sena
       (1'b1), .aclr (n_604), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (raddr[0]));
  CDN_flop \rptr_empty_rbin_reg[1] (.clk (rclk), .d (n_590), .sena
       (1'b1), .aclr (n_604), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (raddr[1]));
  CDN_flop \rptr_empty_rbin_reg[2] (.clk (rclk), .d (n_595), .sena
       (1'b1), .aclr (n_604), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (raddr[2]));
  CDN_flop \rptr_empty_rbin_reg[3] (.clk (rclk), .d (n_598), .sena
       (1'b1), .aclr (n_604), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (raddr[3]));
  CDN_flop \rptr_empty_rbin_reg[4] (.clk (rclk), .d (n_601), .sena
       (1'b1), .aclr (n_604), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (rptr[4]));
  CDN_flop rptr_empty_rempty_reg(.clk (rclk), .d (n_1542), .sena
       (1'b1), .aclr (1'b0), .apre (n_604), .srl (1'b0), .srd (1'b0),
       .q (rempty));
  CDN_flop \rptr_empty_rptr_reg[0] (.clk (rclk), .d (n_592), .sena
       (1'b1), .aclr (n_604), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (rptr[0]));
  CDN_flop \rptr_empty_rptr_reg[1] (.clk (rclk), .d (n_596), .sena
       (1'b1), .aclr (n_604), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (rptr[1]));
  CDN_flop \rptr_empty_rptr_reg[2] (.clk (rclk), .d (n_599), .sena
       (1'b1), .aclr (n_604), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (rptr[2]));
  CDN_flop \rptr_empty_rptr_reg[3] (.clk (rclk), .d (n_602), .sena
       (1'b1), .aclr (n_604), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (rptr[3]));
  not sync_r2w_g1194 (n_603, wrst_n);
  CDN_flop \sync_r2w_wq1_rptr_reg[0] (.clk (wclk), .d (rptr[0]), .sena
       (1'b1), .aclr (n_603), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (sync_r2w_wq1_rptr[0]));
  CDN_flop \sync_r2w_wq1_rptr_reg[1] (.clk (wclk), .d (rptr[1]), .sena
       (1'b1), .aclr (n_603), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (sync_r2w_wq1_rptr[1]));
  CDN_flop \sync_r2w_wq1_rptr_reg[2] (.clk (wclk), .d (rptr[2]), .sena
       (1'b1), .aclr (n_603), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (sync_r2w_wq1_rptr[2]));
  CDN_flop \sync_r2w_wq1_rptr_reg[3] (.clk (wclk), .d (rptr[3]), .sena
       (1'b1), .aclr (n_603), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (sync_r2w_wq1_rptr[3]));
  CDN_flop \sync_r2w_wq1_rptr_reg[4] (.clk (wclk), .d (rptr[4]), .sena
       (1'b1), .aclr (n_603), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (sync_r2w_wq1_rptr[4]));
  CDN_flop \sync_r2w_wq2_rptr_reg[0] (.clk (wclk), .d
       (sync_r2w_wq1_rptr[0]), .sena (1'b1), .aclr (n_603), .apre
       (1'b0), .srl (1'b0), .srd (1'b0), .q (wq2_rptr[0]));
  CDN_flop \sync_r2w_wq2_rptr_reg[1] (.clk (wclk), .d
       (sync_r2w_wq1_rptr[1]), .sena (1'b1), .aclr (n_603), .apre
       (1'b0), .srl (1'b0), .srd (1'b0), .q (wq2_rptr[1]));
  CDN_flop \sync_r2w_wq2_rptr_reg[2] (.clk (wclk), .d
       (sync_r2w_wq1_rptr[2]), .sena (1'b1), .aclr (n_603), .apre
       (1'b0), .srl (1'b0), .srd (1'b0), .q (wq2_rptr[2]));
  CDN_flop \sync_r2w_wq2_rptr_reg[3] (.clk (wclk), .d
       (sync_r2w_wq1_rptr[3]), .sena (1'b1), .aclr (n_603), .apre
       (1'b0), .srl (1'b0), .srd (1'b0), .q (wq2_rptr[3]));
  CDN_flop \sync_r2w_wq2_rptr_reg[4] (.clk (wclk), .d
       (sync_r2w_wq1_rptr[4]), .sena (1'b1), .aclr (n_603), .apre
       (1'b0), .srl (1'b0), .srd (1'b0), .q (wq2_rptr[4]));
  not sync_w2r_g1195 (n_604, rrst_n);
  CDN_flop \sync_w2r_rq1_wptr_reg[0] (.clk (rclk), .d (wptr[0]), .sena
       (1'b1), .aclr (n_604), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (sync_w2r_rq1_wptr[0]));
  CDN_flop \sync_w2r_rq1_wptr_reg[1] (.clk (rclk), .d (wptr[1]), .sena
       (1'b1), .aclr (n_604), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (sync_w2r_rq1_wptr[1]));
  CDN_flop \sync_w2r_rq1_wptr_reg[2] (.clk (rclk), .d (wptr[2]), .sena
       (1'b1), .aclr (n_604), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (sync_w2r_rq1_wptr[2]));
  CDN_flop \sync_w2r_rq1_wptr_reg[3] (.clk (rclk), .d (wptr[3]), .sena
       (1'b1), .aclr (n_604), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (sync_w2r_rq1_wptr[3]));
  CDN_flop \sync_w2r_rq1_wptr_reg[4] (.clk (rclk), .d (wptr[4]), .sena
       (1'b1), .aclr (n_604), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (sync_w2r_rq1_wptr[4]));
  CDN_flop \sync_w2r_rq2_wptr_reg[0] (.clk (rclk), .d
       (sync_w2r_rq1_wptr[0]), .sena (1'b1), .aclr (n_604), .apre
       (1'b0), .srl (1'b0), .srd (1'b0), .q (rq2_wptr[0]));
  CDN_flop \sync_w2r_rq2_wptr_reg[1] (.clk (rclk), .d
       (sync_w2r_rq1_wptr[1]), .sena (1'b1), .aclr (n_604), .apre
       (1'b0), .srl (1'b0), .srd (1'b0), .q (rq2_wptr[1]));
  CDN_flop \sync_w2r_rq2_wptr_reg[2] (.clk (rclk), .d
       (sync_w2r_rq1_wptr[2]), .sena (1'b1), .aclr (n_604), .apre
       (1'b0), .srl (1'b0), .srd (1'b0), .q (rq2_wptr[2]));
  CDN_flop \sync_w2r_rq2_wptr_reg[3] (.clk (rclk), .d
       (sync_w2r_rq1_wptr[3]), .sena (1'b1), .aclr (n_604), .apre
       (1'b0), .srl (1'b0), .srd (1'b0), .q (rq2_wptr[3]));
  CDN_flop \sync_w2r_rq2_wptr_reg[4] (.clk (rclk), .d
       (sync_w2r_rq1_wptr[4]), .sena (1'b1), .aclr (n_604), .apre
       (1'b0), .srl (1'b0), .srd (1'b0), .q (rq2_wptr[4]));
  CDN_flop \wptr_full_wbin_reg[0] (.clk (wclk), .d (n_610), .sena
       (1'b1), .aclr (n_603), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (waddr[0]));
  CDN_flop \wptr_full_wbin_reg[1] (.clk (wclk), .d (n_608), .sena
       (1'b1), .aclr (n_603), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (waddr[1]));
  CDN_flop \wptr_full_wbin_reg[2] (.clk (wclk), .d (n_613), .sena
       (1'b1), .aclr (n_603), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (waddr[2]));
  CDN_flop \wptr_full_wbin_reg[3] (.clk (wclk), .d (n_616), .sena
       (1'b1), .aclr (n_603), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (waddr[3]));
  CDN_flop \wptr_full_wbin_reg[4] (.clk (wclk), .d (n_619), .sena
       (1'b1), .aclr (n_603), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (wptr[4]));
  CDN_flop wptr_full_wfull_reg(.clk (wclk), .d (n_1541), .sena (1'b1),
       .aclr (n_603), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (wfull));
  CDN_flop \wptr_full_wptr_reg[0] (.clk (wclk), .d (n_611), .sena
       (1'b1), .aclr (n_603), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (wptr[0]));
  CDN_flop \wptr_full_wptr_reg[1] (.clk (wclk), .d (n_614), .sena
       (1'b1), .aclr (n_603), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (wptr[1]));
  CDN_flop \wptr_full_wptr_reg[2] (.clk (wclk), .d (n_617), .sena
       (1'b1), .aclr (n_603), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (wptr[2]));
  CDN_flop \wptr_full_wptr_reg[3] (.clk (wclk), .d (n_620), .sena
       (1'b1), .aclr (n_603), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (wptr[3]));
endmodule

`ifdef RC_CDN_GENERIC_GATE
`else
module CDN_flop(clk, d, sena, aclr, apre, srl, srd, q);
  input clk, d, sena, aclr, apre, srl, srd;
  output q;
  wire clk, d, sena, aclr, apre, srl, srd;
  wire q;
  reg  qi;
  assign #1 q = qi;
  always 
    @(posedge clk or posedge apre or posedge aclr) 
      if (aclr) 
        qi <= 0;
      else if (apre) 
          qi <= 1;
        else if (srl) 
            qi <= srd;
          else begin
            if (sena) 
              qi <= d;
          end
  initial 
    qi <= 1'b0;
endmodule
`endif
