
// Generated by Cadence Genus(TM) Synthesis Solution 19.12-s121_1
// Generated on: Apr  6 2022 22:34:20 IST (Apr  6 2022 17:04:20 UTC)

// Verification Directory fv/fifo 

module fifo(rdata, wfull, rempty, wdata, winc, wclk, wrst_n, rinc,
     rclk, rrst_n);
  input [7:0] wdata;
  input winc, wclk, wrst_n, rinc, rclk, rrst_n;
  output [7:0] rdata;
  output wfull, rempty;
  wire [7:0] wdata;
  wire winc, wclk, wrst_n, rinc, rclk, rrst_n;
  wire [7:0] rdata;
  wire wfull, rempty;
  wire [4:0] rq2_wptr;
  wire [4:0] wq2_rptr;
  wire [4:0] sync_w2r_rq1_wptr;
  wire [4:0] wptr;
  wire [4:0] sync_r2w_wq1_rptr;
  wire [4:0] rptr;
  wire [7:0] \fifomem_mem[8] ;
  wire [7:0] \fifomem_mem[12] ;
  wire [7:0] \fifomem_mem[9] ;
  wire [7:0] \fifomem_mem[10] ;
  wire [7:0] \fifomem_mem[14] ;
  wire [7:0] \fifomem_mem[15] ;
  wire [7:0] \fifomem_mem[11] ;
  wire [7:0] \fifomem_mem[6] ;
  wire [7:0] \fifomem_mem[7] ;
  wire [7:0] \fifomem_mem[2] ;
  wire [7:0] \fifomem_mem[3] ;
  wire [7:0] \fifomem_mem[0] ;
  wire [7:0] \fifomem_mem[4] ;
  wire [7:0] \fifomem_mem[5] ;
  wire [7:0] \fifomem_mem[1] ;
  wire [7:0] \fifomem_mem[13] ;
  wire [3:0] waddr;
  wire [3:0] raddr;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_23, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_45, n_46, n_47, n_48, n_49;
  wire n_50, n_51, n_52, n_53, n_54, n_55, n_56, n_57;
  wire n_58, n_59, n_60, n_61, n_62, n_63, n_64, n_65;
  wire n_66, n_67, n_68, n_69, n_70, n_71, n_72, n_73;
  wire n_74, n_75, n_76, n_77, n_78, n_79, n_80, n_81;
  wire n_83, n_84, n_85, n_86, n_87, n_88, n_89, n_90;
  wire n_91, n_92, n_93, n_94, n_95, n_96, n_97, n_99;
  wire n_100, n_101, n_102, n_103, n_104, n_105, n_106, n_107;
  wire n_108, n_109, n_110, n_111, n_112, n_113, n_114, n_115;
  wire n_116, n_118, n_119, n_120, n_121, n_122, n_123, n_124;
  wire n_125, n_126, n_127, n_128, n_129, n_130, n_131, n_132;
  wire n_133, n_134, n_135, n_136, n_137, n_138, n_139, n_140;
  wire n_141, n_142, n_143, n_144, n_145, n_146, n_147, n_148;
  wire n_149, n_151, n_152, n_156, n_159, n_161, n_162, n_167;
  wire n_168, n_169, n_170, n_171, n_172, n_173, n_174, n_175;
  wire n_176, n_177, n_178, n_179, n_180, n_181, n_182, n_183;
  wire n_184, n_191, n_192, n_193, n_194;
  DFQSM2RA rptr_empty_rempty_reg(.SB (rrst_n), .CK (rclk), .D (n_184),
       .Q (rempty));
  NR4B1M1R g4649__2398(.B (n_126), .C (n_181), .D (n_183), .NA (n_171),
       .Z (n_184));
  DFQRM2RA wptr_full_wfull_reg(.RB (wrst_n), .CK (wclk), .D (n_182), .Q
       (wfull));
  OAI221M2R g4651__5107(.A1 (rq2_wptr[1]), .A2 (n_170), .B1
       (rq2_wptr[0]), .B2 (n_169), .C (n_179), .Z (n_183));
  NR4B1M1R g4650__6260(.B (n_191), .C (n_177), .D (n_176), .NA (n_174),
       .Z (n_182));
  MOAI22M2RA g4655__4319(.A1 (n_180), .A2 (rq2_wptr[3]), .B1 (n_180),
       .B2 (rq2_wptr[3]), .Z (n_181));
  MAOI22M2RA g4654__8428(.A1 (n_178), .A2 (rq2_wptr[2]), .B1 (n_178),
       .B2 (rq2_wptr[2]), .Z (n_179));
  OAI221M2R g4653__5526(.A1 (wq2_rptr[1]), .A2 (n_173), .B1
       (wq2_rptr[0]), .B2 (n_172), .C (n_168), .Z (n_177));
  MOAI22M2RA g4652__6783(.A1 (n_175), .A2 (wq2_rptr[3]), .B1 (n_175),
       .B2 (wq2_rptr[3]), .Z (n_176));
  DFQRM2RA \sync_w2r_rq2_wptr_reg[3] (.RB (rrst_n), .CK (rclk), .D
       (sync_w2r_rq1_wptr[3]), .Q (rq2_wptr[3]));
  AOI22M2R g4660__3680(.A1 (n_173), .A2 (wq2_rptr[1]), .B1 (n_172), .B2
       (wq2_rptr[0]), .Z (n_174));
  DFQRM2RA \sync_w2r_rq2_wptr_reg[2] (.RB (rrst_n), .CK (rclk), .D
       (sync_w2r_rq1_wptr[2]), .Q (rq2_wptr[2]));
  AOI22M2R g4666__1617(.A1 (n_170), .A2 (rq2_wptr[1]), .B1 (n_169), .B2
       (rq2_wptr[0]), .Z (n_171));
  MAOI22M2RA g4657__2802(.A1 (n_167), .A2 (wq2_rptr[2]), .B1 (n_167),
       .B2 (wq2_rptr[2]), .Z (n_168));
  DFQRM2RA \sync_w2r_rq1_wptr_reg[3] (.RB (rrst_n), .CK (rclk), .D
       (wptr[3]), .Q (sync_w2r_rq1_wptr[3]));
  DFQRM2RA \sync_r2w_wq2_rptr_reg[3] (.RB (wrst_n), .CK (wclk), .D
       (sync_r2w_wq1_rptr[3]), .Q (wq2_rptr[3]));
  DFQRM2RA \sync_w2r_rq1_wptr_reg[2] (.RB (rrst_n), .CK (rclk), .D
       (wptr[2]), .Q (sync_w2r_rq1_wptr[2]));
  DFQRM2RA \sync_r2w_wq1_rptr_reg[3] (.RB (wrst_n), .CK (wclk), .D
       (rptr[3]), .Q (sync_r2w_wq1_rptr[3]));
  AO221M1RA g4733__1705(.A1 (n_156), .A2 (\fifomem_mem[8] [7]), .B1
       (n_72), .B2 (\fifomem_mem[12] [7]), .C (n_144), .Z (rdata[7]));
  DFQRM2RA \wptr_full_wptr_reg[3] (.RB (wrst_n), .CK (wclk), .D
       (n_175), .Q (wptr[3]));
  DFQRM2RA \sync_r2w_wq2_rptr_reg[1] (.RB (wrst_n), .CK (wclk), .D
       (sync_r2w_wq1_rptr[1]), .Q (wq2_rptr[1]));
  DFQRM2RA \sync_r2w_wq2_rptr_reg[2] (.RB (wrst_n), .CK (wclk), .D
       (sync_r2w_wq1_rptr[2]), .Q (wq2_rptr[2]));
  DFQRM2RA \sync_w2r_rq2_wptr_reg[1] (.RB (rrst_n), .CK (rclk), .D
       (sync_w2r_rq1_wptr[1]), .Q (rq2_wptr[1]));
  AO221M1RA g4728__5122(.A1 (n_143), .A2 (\fifomem_mem[9] [0]), .B1
       (n_159), .B2 (\fifomem_mem[10] [0]), .C (n_151), .Z (rdata[0]));
  AO221M1RA g4734__8246(.A1 (n_162), .A2 (\fifomem_mem[14] [5]), .B1
       (n_161), .B2 (\fifomem_mem[15] [5]), .C (n_140), .Z (rdata[5]));
  AO221M1RA g4731__7098(.A1 (n_162), .A2 (\fifomem_mem[14] [4]), .B1
       (n_161), .B2 (\fifomem_mem[15] [4]), .C (n_148), .Z (rdata[4]));
  AO221M1RA g4735__6131(.A1 (n_159), .A2 (\fifomem_mem[10] [3]), .B1
       (n_147), .B2 (\fifomem_mem[11] [3]), .C (n_152), .Z (rdata[3]));
  AO221M1RA g4729__1881(.A1 (n_99), .A2 (\fifomem_mem[6] [2]), .B1
       (n_145), .B2 (\fifomem_mem[7] [2]), .C (n_142), .Z (rdata[2]));
  AO221M1RA g4730__5115(.A1 (n_156), .A2 (\fifomem_mem[8] [1]), .B1
       (n_161), .B2 (\fifomem_mem[15] [1]), .C (n_141), .Z (rdata[1]));
  AO221M1RA g4732__7482(.A1 (n_94), .A2 (\fifomem_mem[2] [6]), .B1
       (n_88), .B2 (\fifomem_mem[3] [6]), .C (n_146), .Z (rdata[6]));
  DFQRM2RA \wptr_full_wptr_reg[2] (.RB (wrst_n), .CK (wclk), .D
       (n_139), .Q (wptr[2]));
  DFQRM2RA \sync_w2r_rq2_wptr_reg[0] (.RB (rrst_n), .CK (rclk), .D
       (sync_w2r_rq1_wptr[0]), .Q (rq2_wptr[0]));
  DFQRM2RA \sync_w2r_rq1_wptr_reg[1] (.RB (rrst_n), .CK (rclk), .D
       (wptr[1]), .Q (sync_w2r_rq1_wptr[1]));
  AO211M1RA g4805__6161(.A1 (n_161), .A2 (\fifomem_mem[15] [3]), .B
       (n_132), .C (n_35), .Z (n_152));
  DFQRM2RA \sync_r2w_wq1_rptr_reg[1] (.RB (wrst_n), .CK (wclk), .D
       (rptr[1]), .Q (sync_r2w_wq1_rptr[1]));
  AO211M1RA g4804__9315(.A1 (n_156), .A2 (\fifomem_mem[8] [0]), .B
       (n_131), .C (n_49), .Z (n_151));
  DFQRM2RA \rptr_empty_rptr_reg[3] (.RB (rrst_n), .CK (rclk), .D
       (n_137), .Q (rptr[3]));
  DFQRM2RA \sync_r2w_wq2_rptr_reg[0] (.RB (wrst_n), .CK (wclk), .D
       (sync_r2w_wq1_rptr[0]), .Q (wq2_rptr[0]));
  MOAI22M2RA g4689__9945(.A1 (n_192), .A2 (n_149), .B1 (n_192), .B2
       (n_149), .Z (n_175));
  AO211M1RA g4803__2883(.A1 (n_147), .A2 (\fifomem_mem[11] [4]), .B
       (n_130), .C (n_63), .Z (n_148));
  AO211M1RA g4798__2346(.A1 (n_145), .A2 (\fifomem_mem[7] [6]), .B
       (n_127), .C (n_47), .Z (n_146));
  AO211M1RA g4799__1666(.A1 (n_143), .A2 (\fifomem_mem[9] [7]), .B
       (n_133), .C (n_38), .Z (n_144));
  AO211M1RA g4800__7410(.A1 (n_75), .A2 (\fifomem_mem[0] [2]), .B
       (n_128), .C (n_32), .Z (n_142));
  AO211M1RA g4801__6417(.A1 (n_143), .A2 (\fifomem_mem[9] [1]), .B
       (n_134), .C (n_62), .Z (n_141));
  AO211M1RA g4802__5477(.A1 (n_156), .A2 (\fifomem_mem[8] [5]), .B
       (n_129), .C (n_60), .Z (n_140));
  DFQRM2RA \sync_r2w_wq1_rptr_reg[2] (.RB (wrst_n), .CK (wclk), .D
       (rptr[2]), .Q (sync_r2w_wq1_rptr[2]));
  DFQRM2RA \sync_w2r_rq1_wptr_reg[0] (.RB (rrst_n), .CK (rclk), .D
       (wptr[0]), .Q (sync_w2r_rq1_wptr[0]));
  CKINVM1R g4686(.A (n_167), .Z (n_139));
  SDFQM2RA \fifomem_mem_reg[6][0] (.CK (wclk), .D (wdata[0]), .SD
       (\fifomem_mem[6] [0]), .SE (n_138), .Q (\fifomem_mem[6] [0]));
  DFQRM2RA \wptr_full_wbin_reg[4] (.RB (wrst_n), .CK (wclk), .D
       (n_192), .Q (wptr[4]));
  SDFQM2RA \fifomem_mem_reg[6][2] (.CK (wclk), .D (wdata[2]), .SD
       (\fifomem_mem[6] [2]), .SE (n_138), .Q (\fifomem_mem[6] [2]));
  SDFQM2RA \fifomem_mem_reg[6][4] (.CK (wclk), .D (wdata[4]), .SD
       (\fifomem_mem[6] [4]), .SE (n_138), .Q (\fifomem_mem[6] [4]));
  SDFQM2RA \fifomem_mem_reg[6][3] (.CK (wclk), .D (wdata[3]), .SD
       (\fifomem_mem[6] [3]), .SE (n_138), .Q (\fifomem_mem[6] [3]));
  SDFQM2RA \fifomem_mem_reg[6][6] (.CK (wclk), .D (wdata[6]), .SD
       (\fifomem_mem[6] [6]), .SE (n_138), .Q (\fifomem_mem[6] [6]));
  SDFQM2RA \fifomem_mem_reg[6][5] (.CK (wclk), .D (wdata[5]), .SD
       (\fifomem_mem[6] [5]), .SE (n_138), .Q (\fifomem_mem[6] [5]));
  SDFQM2RA \fifomem_mem_reg[6][7] (.CK (wclk), .D (wdata[7]), .SD
       (\fifomem_mem[6] [7]), .SE (n_138), .Q (\fifomem_mem[6] [7]));
  SDFQM2RA \fifomem_mem_reg[6][1] (.CK (wclk), .D (wdata[1]), .SD
       (\fifomem_mem[6] [1]), .SE (n_138), .Q (\fifomem_mem[6] [1]));
  DFQRM1RA \wptr_full_wptr_reg[1] (.RB (wrst_n), .CK (wclk), .D
       (n_115), .Q (wptr[1]));
  CKINVM1R g4674(.A (n_180), .Z (n_137));
  DFQRM2RA \rptr_empty_rptr_reg[1] (.RB (rrst_n), .CK (rclk), .D
       (n_112), .Q (rptr[1]));
  DFQRM2RA \sync_r2w_wq1_rptr_reg[0] (.RB (wrst_n), .CK (wclk), .D
       (rptr[0]), .Q (sync_r2w_wq1_rptr[0]));
  DFQRM2RA \rptr_empty_rptr_reg[2] (.RB (rrst_n), .CK (rclk), .D
       (n_114), .Q (rptr[2]));
  SDFQM1RA \fifomem_mem_reg[2][7] (.CK (wclk), .D (\fifomem_mem[2]
       [7]), .SD (wdata[7]), .SE (n_136), .Q (\fifomem_mem[2] [7]));
  SDFQM1RA \fifomem_mem_reg[2][3] (.CK (wclk), .D (\fifomem_mem[2]
       [3]), .SD (wdata[3]), .SE (n_136), .Q (\fifomem_mem[2] [3]));
  MAOI22M2RA g4690__2398(.A1 (n_149), .A2 (n_135), .B1 (n_149), .B2
       (n_135), .Z (n_167));
  SDFQM1RA \fifomem_mem_reg[2][0] (.CK (wclk), .D (\fifomem_mem[2]
       [0]), .SD (wdata[0]), .SE (n_136), .Q (\fifomem_mem[2] [0]));
  SDFQM1RA \fifomem_mem_reg[2][5] (.CK (wclk), .D (\fifomem_mem[2]
       [5]), .SD (wdata[5]), .SE (n_136), .Q (\fifomem_mem[2] [5]));
  SDFQM1RA \fifomem_mem_reg[2][6] (.CK (wclk), .D (\fifomem_mem[2]
       [6]), .SD (wdata[6]), .SE (n_136), .Q (\fifomem_mem[2] [6]));
  SDFQM1RA \fifomem_mem_reg[2][4] (.CK (wclk), .D (\fifomem_mem[2]
       [4]), .SD (wdata[4]), .SE (n_136), .Q (\fifomem_mem[2] [4]));
  SDFQM1RA \fifomem_mem_reg[2][1] (.CK (wclk), .D (\fifomem_mem[2]
       [1]), .SD (wdata[1]), .SE (n_136), .Q (\fifomem_mem[2] [1]));
  SDFQM1RA \fifomem_mem_reg[2][2] (.CK (wclk), .D (\fifomem_mem[2]
       [2]), .SD (wdata[2]), .SE (n_136), .Q (\fifomem_mem[2] [2]));
  DFQRM2RA \wptr_full_wptr_reg[0] (.RB (wrst_n), .CK (wclk), .D
       (n_111), .Q (wptr[0]));
  ND4M2R g4861__5107(.A (n_89), .B (n_69), .C (n_43), .D (n_42), .Z
       (n_134));
  ND4M2R g4862__6260(.A (n_93), .B (n_74), .C (n_36), .D (n_31), .Z
       (n_133));
  ND4M2R g4863__4319(.A (n_100), .B (n_77), .C (n_64), .D (n_61), .Z
       (n_132));
  ND4M2R g4864__8428(.A (n_95), .B (n_66), .C (n_30), .D (n_33), .Z
       (n_131));
  ND4M2R g4865__5526(.A (n_86), .B (n_68), .C (n_34), .D (n_56), .Z
       (n_130));
  ND4M2R g4866__6783(.A (n_87), .B (n_73), .C (n_57), .D (n_55), .Z
       (n_129));
  ND4M2R g4867__3680(.A (n_91), .B (n_70), .C (n_53), .D (n_52), .Z
       (n_128));
  ND4M2R g4868__1617(.A (n_90), .B (n_76), .C (n_37), .D (n_40), .Z
       (n_127));
  MAOI22M2RA g4675__2802(.A1 (n_125), .A2 (rq2_wptr[4]), .B1 (n_125),
       .B2 (rq2_wptr[4]), .Z (n_126));
  SDFQM2RA \fifomem_mem_reg[0][7] (.CK (wclk), .D (wdata[7]), .SD
       (\fifomem_mem[0] [7]), .SE (n_124), .Q (\fifomem_mem[0] [7]));
  SDFQM1RA \fifomem_mem_reg[15][4] (.CK (wclk), .D (\fifomem_mem[15]
       [4]), .SD (wdata[4]), .SE (n_121), .Q (\fifomem_mem[15] [4]));
  SDFQM2RA \fifomem_mem_reg[0][0] (.CK (wclk), .D (wdata[0]), .SD
       (\fifomem_mem[0] [0]), .SE (n_124), .Q (\fifomem_mem[0] [0]));
  SDFQM2RA \fifomem_mem_reg[4][3] (.CK (wclk), .D (wdata[3]), .SD
       (\fifomem_mem[4] [3]), .SE (n_123), .Q (\fifomem_mem[4] [3]));
  SDFQM2RA \fifomem_mem_reg[4][2] (.CK (wclk), .D (wdata[2]), .SD
       (\fifomem_mem[4] [2]), .SE (n_123), .Q (\fifomem_mem[4] [2]));
  SDFQM1RA \fifomem_mem_reg[7][1] (.CK (wclk), .D (\fifomem_mem[7]
       [1]), .SD (wdata[1]), .SE (n_122), .Q (\fifomem_mem[7] [1]));
  SDFQM1RA \fifomem_mem_reg[7][2] (.CK (wclk), .D (\fifomem_mem[7]
       [2]), .SD (wdata[2]), .SE (n_122), .Q (\fifomem_mem[7] [2]));
  SDFQM1RA \fifomem_mem_reg[7][3] (.CK (wclk), .D (\fifomem_mem[7]
       [3]), .SD (wdata[3]), .SE (n_122), .Q (\fifomem_mem[7] [3]));
  SDFQM1RA \fifomem_mem_reg[7][6] (.CK (wclk), .D (\fifomem_mem[7]
       [6]), .SD (wdata[6]), .SE (n_122), .Q (\fifomem_mem[7] [6]));
  SDFQM1RA \fifomem_mem_reg[7][7] (.CK (wclk), .D (\fifomem_mem[7]
       [7]), .SD (wdata[7]), .SE (n_122), .Q (\fifomem_mem[7] [7]));
  SDFQM1RA \fifomem_mem_reg[7][0] (.CK (wclk), .D (\fifomem_mem[7]
       [0]), .SD (wdata[0]), .SE (n_122), .Q (\fifomem_mem[7] [0]));
  SDFQM1RA \fifomem_mem_reg[7][5] (.CK (wclk), .D (\fifomem_mem[7]
       [5]), .SD (wdata[5]), .SE (n_122), .Q (\fifomem_mem[7] [5]));
  SDFQM1RA \fifomem_mem_reg[7][4] (.CK (wclk), .D (\fifomem_mem[7]
       [4]), .SD (wdata[4]), .SE (n_122), .Q (\fifomem_mem[7] [4]));
  SDFQM1RA \fifomem_mem_reg[15][2] (.CK (wclk), .D (\fifomem_mem[15]
       [2]), .SD (wdata[2]), .SE (n_121), .Q (\fifomem_mem[15] [2]));
  SDFQM1RA \fifomem_mem_reg[15][3] (.CK (wclk), .D (\fifomem_mem[15]
       [3]), .SD (wdata[3]), .SE (n_121), .Q (\fifomem_mem[15] [3]));
  SDFQM1RA \fifomem_mem_reg[15][7] (.CK (wclk), .D (\fifomem_mem[15]
       [7]), .SD (wdata[7]), .SE (n_121), .Q (\fifomem_mem[15] [7]));
  SDFQM1RA \fifomem_mem_reg[15][0] (.CK (wclk), .D (\fifomem_mem[15]
       [0]), .SD (wdata[0]), .SE (n_121), .Q (\fifomem_mem[15] [0]));
  SDFQM1RA \fifomem_mem_reg[15][1] (.CK (wclk), .D (\fifomem_mem[15]
       [1]), .SD (wdata[1]), .SE (n_121), .Q (\fifomem_mem[15] [1]));
  SDFQM1RA \fifomem_mem_reg[15][5] (.CK (wclk), .D (\fifomem_mem[15]
       [5]), .SD (wdata[5]), .SE (n_121), .Q (\fifomem_mem[15] [5]));
  SDFQM1RA \fifomem_mem_reg[15][6] (.CK (wclk), .D (\fifomem_mem[15]
       [6]), .SD (wdata[6]), .SE (n_121), .Q (\fifomem_mem[15] [6]));
  SDFQM1RA \fifomem_mem_reg[5][7] (.CK (wclk), .D (\fifomem_mem[5]
       [7]), .SD (wdata[7]), .SE (n_119), .Q (\fifomem_mem[5] [7]));
  SDFQM2RA \fifomem_mem_reg[4][0] (.CK (wclk), .D (wdata[0]), .SD
       (\fifomem_mem[4] [0]), .SE (n_123), .Q (\fifomem_mem[4] [0]));
  MAOI22M2RA g4681__1705(.A1 (n_125), .A2 (n_120), .B1 (n_125), .B2
       (n_120), .Z (n_180));
  SDFQM2RA \fifomem_mem_reg[4][4] (.CK (wclk), .D (wdata[4]), .SD
       (\fifomem_mem[4] [4]), .SE (n_123), .Q (\fifomem_mem[4] [4]));
  SDFQM2RA \fifomem_mem_reg[4][7] (.CK (wclk), .D (wdata[7]), .SD
       (\fifomem_mem[4] [7]), .SE (n_123), .Q (\fifomem_mem[4] [7]));
  SDFQM1RA \fifomem_mem_reg[5][0] (.CK (wclk), .D (\fifomem_mem[5]
       [0]), .SD (wdata[0]), .SE (n_119), .Q (\fifomem_mem[5] [0]));
  SDFQM1RA \fifomem_mem_reg[5][1] (.CK (wclk), .D (\fifomem_mem[5]
       [1]), .SD (wdata[1]), .SE (n_119), .Q (\fifomem_mem[5] [1]));
  SDFQM1RA \fifomem_mem_reg[5][2] (.CK (wclk), .D (\fifomem_mem[5]
       [2]), .SD (wdata[2]), .SE (n_119), .Q (\fifomem_mem[5] [2]));
  SDFQM1RA \fifomem_mem_reg[5][3] (.CK (wclk), .D (\fifomem_mem[5]
       [3]), .SD (wdata[3]), .SE (n_119), .Q (\fifomem_mem[5] [3]));
  SDFQM1RA \fifomem_mem_reg[5][4] (.CK (wclk), .D (\fifomem_mem[5]
       [4]), .SD (wdata[4]), .SE (n_119), .Q (\fifomem_mem[5] [4]));
  SDFQM1RA \fifomem_mem_reg[5][5] (.CK (wclk), .D (\fifomem_mem[5]
       [5]), .SD (wdata[5]), .SE (n_119), .Q (\fifomem_mem[5] [5]));
  SDFQM2RA \fifomem_mem_reg[4][6] (.CK (wclk), .D (wdata[6]), .SD
       (\fifomem_mem[4] [6]), .SE (n_123), .Q (\fifomem_mem[4] [6]));
  SDFQM1RA \fifomem_mem_reg[5][6] (.CK (wclk), .D (\fifomem_mem[5]
       [6]), .SD (wdata[6]), .SE (n_119), .Q (\fifomem_mem[5] [6]));
  SDFQM2RA \fifomem_mem_reg[0][2] (.CK (wclk), .D (wdata[2]), .SD
       (\fifomem_mem[0] [2]), .SE (n_124), .Q (\fifomem_mem[0] [2]));
  SDFQM2RA \fifomem_mem_reg[0][3] (.CK (wclk), .D (wdata[3]), .SD
       (\fifomem_mem[0] [3]), .SE (n_124), .Q (\fifomem_mem[0] [3]));
  SDFQM2RA \fifomem_mem_reg[0][6] (.CK (wclk), .D (wdata[6]), .SD
       (\fifomem_mem[0] [6]), .SE (n_124), .Q (\fifomem_mem[0] [6]));
  SDFQM1RA \fifomem_mem_reg[1][0] (.CK (wclk), .D (\fifomem_mem[1]
       [0]), .SD (wdata[0]), .SE (n_118), .Q (\fifomem_mem[1] [0]));
  SDFQM1RA \fifomem_mem_reg[1][1] (.CK (wclk), .D (\fifomem_mem[1]
       [1]), .SD (wdata[1]), .SE (n_118), .Q (\fifomem_mem[1] [1]));
  SDFQM2RA \fifomem_mem_reg[0][1] (.CK (wclk), .D (wdata[1]), .SD
       (\fifomem_mem[0] [1]), .SE (n_124), .Q (\fifomem_mem[0] [1]));
  SDFQM2RA \fifomem_mem_reg[0][5] (.CK (wclk), .D (wdata[5]), .SD
       (\fifomem_mem[0] [5]), .SE (n_124), .Q (\fifomem_mem[0] [5]));
  SDFQM1RA \fifomem_mem_reg[1][2] (.CK (wclk), .D (\fifomem_mem[1]
       [2]), .SD (wdata[2]), .SE (n_118), .Q (\fifomem_mem[1] [2]));
  SDFQM1RA \fifomem_mem_reg[1][4] (.CK (wclk), .D (\fifomem_mem[1]
       [4]), .SD (wdata[4]), .SE (n_118), .Q (\fifomem_mem[1] [4]));
  SDFQM1RA \fifomem_mem_reg[1][5] (.CK (wclk), .D (\fifomem_mem[1]
       [5]), .SD (wdata[5]), .SE (n_118), .Q (\fifomem_mem[1] [5]));
  SDFQM1RA \fifomem_mem_reg[1][6] (.CK (wclk), .D (\fifomem_mem[1]
       [6]), .SD (wdata[6]), .SE (n_118), .Q (\fifomem_mem[1] [6]));
  SDFQM1RA \fifomem_mem_reg[1][3] (.CK (wclk), .D (\fifomem_mem[1]
       [3]), .SD (wdata[3]), .SE (n_118), .Q (\fifomem_mem[1] [3]));
  SDFQM2RA \fifomem_mem_reg[0][4] (.CK (wclk), .D (wdata[4]), .SD
       (\fifomem_mem[0] [4]), .SE (n_124), .Q (\fifomem_mem[0] [4]));
  SDFQM1RA \fifomem_mem_reg[3][0] (.CK (wclk), .D (\fifomem_mem[3]
       [0]), .SD (wdata[0]), .SE (n_194), .Q (\fifomem_mem[3] [0]));
  SDFQM1RA \fifomem_mem_reg[3][3] (.CK (wclk), .D (\fifomem_mem[3]
       [3]), .SD (wdata[3]), .SE (n_194), .Q (\fifomem_mem[3] [3]));
  SDFQM1RA \fifomem_mem_reg[3][1] (.CK (wclk), .D (\fifomem_mem[3]
       [1]), .SD (wdata[1]), .SE (n_194), .Q (\fifomem_mem[3] [1]));
  SDFQM1RA \fifomem_mem_reg[3][4] (.CK (wclk), .D (\fifomem_mem[3]
       [4]), .SD (wdata[4]), .SE (n_194), .Q (\fifomem_mem[3] [4]));
  SDFQM1RA \fifomem_mem_reg[3][6] (.CK (wclk), .D (\fifomem_mem[3]
       [6]), .SD (wdata[6]), .SE (n_194), .Q (\fifomem_mem[3] [6]));
  SDFQM1RA \fifomem_mem_reg[3][2] (.CK (wclk), .D (\fifomem_mem[3]
       [2]), .SD (wdata[2]), .SE (n_194), .Q (\fifomem_mem[3] [2]));
  SDFQM1RA \fifomem_mem_reg[3][7] (.CK (wclk), .D (\fifomem_mem[3]
       [7]), .SD (wdata[7]), .SE (n_194), .Q (\fifomem_mem[3] [7]));
  SDFQM1RA \fifomem_mem_reg[3][5] (.CK (wclk), .D (\fifomem_mem[3]
       [5]), .SD (wdata[5]), .SE (n_194), .Q (\fifomem_mem[3] [5]));
  SDFQM1RA \fifomem_mem_reg[1][7] (.CK (wclk), .D (\fifomem_mem[1]
       [7]), .SD (wdata[7]), .SE (n_118), .Q (\fifomem_mem[1] [7]));
  SDFQM2RA \fifomem_mem_reg[4][5] (.CK (wclk), .D (wdata[5]), .SD
       (\fifomem_mem[4] [5]), .SE (n_123), .Q (\fifomem_mem[4] [5]));
  SDFQM2RA \fifomem_mem_reg[4][1] (.CK (wclk), .D (wdata[1]), .SD
       (\fifomem_mem[4] [1]), .SE (n_123), .Q (\fifomem_mem[4] [1]));
  DFQRM2RA \rptr_empty_rptr_reg[0] (.RB (rrst_n), .CK (rclk), .D
       (n_101), .Q (rptr[0]));
  CKINVM1R g4764(.A (n_149), .Z (n_116));
  INVM1R g4837(.A (n_173), .Z (n_115));
  INVM1R g4727(.A (n_178), .Z (n_114));
  SDFQM2RA \fifomem_mem_reg[14][5] (.CK (wclk), .D (wdata[5]), .SD
       (\fifomem_mem[14] [5]), .SE (n_113), .Q (\fifomem_mem[14] [5]));
  SDFQM2RA \fifomem_mem_reg[14][0] (.CK (wclk), .D (wdata[0]), .SD
       (\fifomem_mem[14] [0]), .SE (n_113), .Q (\fifomem_mem[14] [0]));
  DFQRM2RA \rptr_empty_rbin_reg[4] (.RB (rrst_n), .CK (rclk), .D
       (n_125), .Q (rptr[4]));
  CKINVM1R g4796(.A (n_170), .Z (n_112));
  SDFQM2RA \fifomem_mem_reg[14][3] (.CK (wclk), .D (wdata[3]), .SD
       (\fifomem_mem[14] [3]), .SE (n_113), .Q (\fifomem_mem[14] [3]));
  SDFQM2RA \fifomem_mem_reg[14][4] (.CK (wclk), .D (wdata[4]), .SD
       (\fifomem_mem[14] [4]), .SE (n_113), .Q (\fifomem_mem[14] [4]));
  SDFQM2RA \fifomem_mem_reg[14][7] (.CK (wclk), .D (wdata[7]), .SD
       (\fifomem_mem[14] [7]), .SE (n_113), .Q (\fifomem_mem[14] [7]));
  SDFQM2RA \fifomem_mem_reg[14][6] (.CK (wclk), .D (wdata[6]), .SD
       (\fifomem_mem[14] [6]), .SE (n_113), .Q (\fifomem_mem[14] [6]));
  SDFQM2RA \fifomem_mem_reg[14][1] (.CK (wclk), .D (wdata[1]), .SD
       (\fifomem_mem[14] [1]), .SE (n_113), .Q (\fifomem_mem[14] [1]));
  SDFQM2RA \fifomem_mem_reg[14][2] (.CK (wclk), .D (wdata[2]), .SD
       (\fifomem_mem[14] [2]), .SE (n_113), .Q (\fifomem_mem[14] [2]));
  CKINVM1R g4859(.A (n_172), .Z (n_111));
  SDFQM2RA \fifomem_mem_reg[13][1] (.CK (wclk), .D (wdata[1]), .SD
       (\fifomem_mem[13] [1]), .SE (n_110), .Q (\fifomem_mem[13] [1]));
  SDFQM1RA \fifomem_mem_reg[10][7] (.CK (wclk), .D (\fifomem_mem[10]
       [7]), .SD (wdata[7]), .SE (n_109), .Q (\fifomem_mem[10] [7]));
  SDFQM2RA \fifomem_mem_reg[13][6] (.CK (wclk), .D (wdata[6]), .SD
       (\fifomem_mem[13] [6]), .SE (n_110), .Q (\fifomem_mem[13] [6]));
  SDFQM1RA \fifomem_mem_reg[10][3] (.CK (wclk), .D (\fifomem_mem[10]
       [3]), .SD (wdata[3]), .SE (n_109), .Q (\fifomem_mem[10] [3]));
  SDFQM2RA \fifomem_mem_reg[9][5] (.CK (wclk), .D (wdata[5]), .SD
       (\fifomem_mem[9] [5]), .SE (n_108), .Q (\fifomem_mem[9] [5]));
  SDFQM2RA \fifomem_mem_reg[9][7] (.CK (wclk), .D (wdata[7]), .SD
       (\fifomem_mem[9] [7]), .SE (n_108), .Q (\fifomem_mem[9] [7]));
  SDFQM2RA \fifomem_mem_reg[13][0] (.CK (wclk), .D (wdata[0]), .SD
       (\fifomem_mem[13] [0]), .SE (n_110), .Q (\fifomem_mem[13] [0]));
  SDFQM2RA \fifomem_mem_reg[9][4] (.CK (wclk), .D (wdata[4]), .SD
       (\fifomem_mem[9] [4]), .SE (n_108), .Q (\fifomem_mem[9] [4]));
  SDFQM2RA \fifomem_mem_reg[9][2] (.CK (wclk), .D (wdata[2]), .SD
       (\fifomem_mem[9] [2]), .SE (n_108), .Q (\fifomem_mem[9] [2]));
  SDFQM2RA \fifomem_mem_reg[11][4] (.CK (wclk), .D (wdata[4]), .SD
       (\fifomem_mem[11] [4]), .SE (n_107), .Q (\fifomem_mem[11] [4]));
  SDFQM2RA \fifomem_mem_reg[9][1] (.CK (wclk), .D (wdata[1]), .SD
       (\fifomem_mem[9] [1]), .SE (n_108), .Q (\fifomem_mem[9] [1]));
  SDFQM1RA \fifomem_mem_reg[8][3] (.CK (wclk), .D (\fifomem_mem[8]
       [3]), .SD (wdata[3]), .SE (n_106), .Q (\fifomem_mem[8] [3]));
  SDFQM2RA \fifomem_mem_reg[9][3] (.CK (wclk), .D (wdata[3]), .SD
       (\fifomem_mem[9] [3]), .SE (n_108), .Q (\fifomem_mem[9] [3]));
  SDFQM1RA \fifomem_mem_reg[12][4] (.CK (wclk), .D (\fifomem_mem[12]
       [4]), .SD (wdata[4]), .SE (n_102), .Q (\fifomem_mem[12] [4]));
  SDFQM2RA \fifomem_mem_reg[11][0] (.CK (wclk), .D (wdata[0]), .SD
       (\fifomem_mem[11] [0]), .SE (n_107), .Q (\fifomem_mem[11] [0]));
  SDFQM2RA \fifomem_mem_reg[9][0] (.CK (wclk), .D (wdata[0]), .SD
       (\fifomem_mem[9] [0]), .SE (n_108), .Q (\fifomem_mem[9] [0]));
  SDFQM1RA \fifomem_mem_reg[8][1] (.CK (wclk), .D (\fifomem_mem[8]
       [1]), .SD (wdata[1]), .SE (n_106), .Q (\fifomem_mem[8] [1]));
  SDFQM1RA \fifomem_mem_reg[8][2] (.CK (wclk), .D (\fifomem_mem[8]
       [2]), .SD (wdata[2]), .SE (n_106), .Q (\fifomem_mem[8] [2]));
  SDFQM1RA \fifomem_mem_reg[8][4] (.CK (wclk), .D (\fifomem_mem[8]
       [4]), .SD (wdata[4]), .SE (n_106), .Q (\fifomem_mem[8] [4]));
  SDFQM1RA \fifomem_mem_reg[8][5] (.CK (wclk), .D (\fifomem_mem[8]
       [5]), .SD (wdata[5]), .SE (n_106), .Q (\fifomem_mem[8] [5]));
  SDFQM1RA \fifomem_mem_reg[8][6] (.CK (wclk), .D (\fifomem_mem[8]
       [6]), .SD (wdata[6]), .SE (n_106), .Q (\fifomem_mem[8] [6]));
  MAOI22M2RA g4762__8246(.A1 (n_120), .A2 (n_105), .B1 (n_120), .B2
       (n_105), .Z (n_178));
  MAOI22M2RA g4827__7098(.A1 (n_105), .A2 (n_104), .B1 (n_105), .B2
       (n_104), .Z (n_170));
  MAOI22M2RA g4843__6131(.A1 (n_135), .A2 (n_103), .B1 (n_135), .B2
       (n_103), .Z (n_173));
  AOI21M2R g4844__1881(.A1 (n_78), .A2 (waddr[3]), .B (n_122), .Z
       (n_149));
  ND2M2R g4874__5115(.A (n_83), .B (waddr[2]), .Z (n_138));
  SDFQM1RA \fifomem_mem_reg[8][7] (.CK (wclk), .D (\fifomem_mem[8]
       [7]), .SD (wdata[7]), .SE (n_106), .Q (\fifomem_mem[8] [7]));
  SDFQM1RA \fifomem_mem_reg[10][0] (.CK (wclk), .D (\fifomem_mem[10]
       [0]), .SD (wdata[0]), .SE (n_109), .Q (\fifomem_mem[10] [0]));
  SDFQM1RA \fifomem_mem_reg[10][1] (.CK (wclk), .D (\fifomem_mem[10]
       [1]), .SD (wdata[1]), .SE (n_109), .Q (\fifomem_mem[10] [1]));
  SDFQM1RA \fifomem_mem_reg[10][2] (.CK (wclk), .D (\fifomem_mem[10]
       [2]), .SD (wdata[2]), .SE (n_109), .Q (\fifomem_mem[10] [2]));
  SDFQM1RA \fifomem_mem_reg[10][4] (.CK (wclk), .D (\fifomem_mem[10]
       [4]), .SD (wdata[4]), .SE (n_109), .Q (\fifomem_mem[10] [4]));
  SDFQM1RA \fifomem_mem_reg[10][5] (.CK (wclk), .D (\fifomem_mem[10]
       [5]), .SD (wdata[5]), .SE (n_109), .Q (\fifomem_mem[10] [5]));
  SDFQM1RA \fifomem_mem_reg[10][6] (.CK (wclk), .D (\fifomem_mem[10]
       [6]), .SD (wdata[6]), .SE (n_109), .Q (\fifomem_mem[10] [6]));
  SDFQM1RA \fifomem_mem_reg[12][0] (.CK (wclk), .D (\fifomem_mem[12]
       [0]), .SD (wdata[0]), .SE (n_102), .Q (\fifomem_mem[12] [0]));
  SDFQM1RA \fifomem_mem_reg[12][1] (.CK (wclk), .D (\fifomem_mem[12]
       [1]), .SD (wdata[1]), .SE (n_102), .Q (\fifomem_mem[12] [1]));
  SDFQM1RA \fifomem_mem_reg[12][2] (.CK (wclk), .D (\fifomem_mem[12]
       [2]), .SD (wdata[2]), .SE (n_102), .Q (\fifomem_mem[12] [2]));
  SDFQM2RA \fifomem_mem_reg[13][3] (.CK (wclk), .D (wdata[3]), .SD
       (\fifomem_mem[13] [3]), .SE (n_110), .Q (\fifomem_mem[13] [3]));
  SDFQM2RA \fifomem_mem_reg[13][4] (.CK (wclk), .D (wdata[4]), .SD
       (\fifomem_mem[13] [4]), .SE (n_110), .Q (\fifomem_mem[13] [4]));
  SDFQM2RA \fifomem_mem_reg[13][7] (.CK (wclk), .D (wdata[7]), .SD
       (\fifomem_mem[13] [7]), .SE (n_110), .Q (\fifomem_mem[13] [7]));
  SDFQM2RA \fifomem_mem_reg[9][6] (.CK (wclk), .D (wdata[6]), .SD
       (\fifomem_mem[9] [6]), .SE (n_108), .Q (\fifomem_mem[9] [6]));
  SDFQM1RA \fifomem_mem_reg[12][3] (.CK (wclk), .D (\fifomem_mem[12]
       [3]), .SD (wdata[3]), .SE (n_102), .Q (\fifomem_mem[12] [3]));
  SDFQM1RA \fifomem_mem_reg[12][5] (.CK (wclk), .D (\fifomem_mem[12]
       [5]), .SD (wdata[5]), .SE (n_102), .Q (\fifomem_mem[12] [5]));
  SDFQM1RA \fifomem_mem_reg[12][6] (.CK (wclk), .D (\fifomem_mem[12]
       [6]), .SD (wdata[6]), .SE (n_102), .Q (\fifomem_mem[12] [6]));
  SDFQM1RA \fifomem_mem_reg[12][7] (.CK (wclk), .D (\fifomem_mem[12]
       [7]), .SD (wdata[7]), .SE (n_102), .Q (\fifomem_mem[12] [7]));
  SDFQM2RA \fifomem_mem_reg[13][2] (.CK (wclk), .D (wdata[2]), .SD
       (\fifomem_mem[13] [2]), .SE (n_110), .Q (\fifomem_mem[13] [2]));
  SDFQM2RA \fifomem_mem_reg[11][1] (.CK (wclk), .D (wdata[1]), .SD
       (\fifomem_mem[11] [1]), .SE (n_107), .Q (\fifomem_mem[11] [1]));
  SDFQM2RA \fifomem_mem_reg[11][2] (.CK (wclk), .D (wdata[2]), .SD
       (\fifomem_mem[11] [2]), .SE (n_107), .Q (\fifomem_mem[11] [2]));
  SDFQM2RA \fifomem_mem_reg[11][3] (.CK (wclk), .D (wdata[3]), .SD
       (\fifomem_mem[11] [3]), .SE (n_107), .Q (\fifomem_mem[11] [3]));
  SDFQM2RA \fifomem_mem_reg[11][5] (.CK (wclk), .D (wdata[5]), .SD
       (\fifomem_mem[11] [5]), .SE (n_107), .Q (\fifomem_mem[11] [5]));
  SDFQM2RA \fifomem_mem_reg[11][6] (.CK (wclk), .D (wdata[6]), .SD
       (\fifomem_mem[11] [6]), .SE (n_107), .Q (\fifomem_mem[11] [6]));
  SDFQM2RA \fifomem_mem_reg[11][7] (.CK (wclk), .D (wdata[7]), .SD
       (\fifomem_mem[11] [7]), .SE (n_107), .Q (\fifomem_mem[11] [7]));
  SDFQM2RA \fifomem_mem_reg[13][5] (.CK (wclk), .D (wdata[5]), .SD
       (\fifomem_mem[13] [5]), .SE (n_110), .Q (\fifomem_mem[13] [5]));
  SDFQM1RA \fifomem_mem_reg[8][0] (.CK (wclk), .D (\fifomem_mem[8]
       [0]), .SD (wdata[0]), .SE (n_106), .Q (\fifomem_mem[8] [0]));
  CKINVM1R g4836(.A (n_169), .Z (n_101));
  AOI221M2R g4907__7482(.A1 (n_99), .A2 (\fifomem_mem[6] [3]), .B1
       (n_92), .B2 (\fifomem_mem[5] [3]), .C (n_45), .Z (n_100));
  MAOI22M2RA g4869__4733(.A1 (n_103), .A2 (n_97), .B1 (n_103), .B2
       (n_97), .Z (n_172));
  MOAI22M2RA g4763__6161(.A1 (n_96), .A2 (rptr[4]), .B1 (n_96), .B2
       (rptr[4]), .Z (n_125));
  NR2M2R g4872__9315(.A (waddr[2]), .B (n_193), .Z (n_136));
  AOI221M2R g4897__9945(.A1 (n_147), .A2 (\fifomem_mem[11] [0]), .B1
       (n_94), .B2 (\fifomem_mem[2] [0]), .C (n_50), .Z (n_95));
  AOI221M2R g4906__2883(.A1 (n_92), .A2 (\fifomem_mem[5] [7]), .B1
       (n_94), .B2 (\fifomem_mem[2] [7]), .C (n_39), .Z (n_93));
  AOI221M2R g4895__2346(.A1 (n_159), .A2 (\fifomem_mem[10] [2]), .B1
       (n_71), .B2 (\fifomem_mem[13] [2]), .C (n_41), .Z (n_91));
  AOI221M2R g4896__1666(.A1 (n_159), .A2 (\fifomem_mem[10] [6]), .B1
       (n_156), .B2 (\fifomem_mem[8] [6]), .C (n_59), .Z (n_90));
  AOI221M2R g4893__7410(.A1 (n_99), .A2 (\fifomem_mem[6] [1]), .B1
       (n_88), .B2 (\fifomem_mem[3] [1]), .C (n_51), .Z (n_89));
  AOI221M2R g4898__6417(.A1 (n_147), .A2 (\fifomem_mem[11] [5]), .B1
       (n_94), .B2 (\fifomem_mem[2] [5]), .C (n_48), .Z (n_87));
  AOI221M2R g4905__5477(.A1 (n_99), .A2 (\fifomem_mem[6] [4]), .B1
       (n_92), .B2 (\fifomem_mem[5] [4]), .C (n_46), .Z (n_86));
  CKINVM1R g4829(.A (n_120), .Z (n_85));
  MAOI22M2RA g4842__2398(.A1 (n_104), .A2 (n_84), .B1 (n_104), .B2
       (n_84), .Z (n_169));
  ND2M2R g4855__6260(.A (n_81), .B (waddr[2]), .Z (n_123));
  CKINVM1R g4882(.A (n_193), .Z (n_83));
  ND2M2R g4857__4319(.A (n_81), .B (n_80), .Z (n_124));
  NR2M2R g4856__8428(.A (waddr[2]), .B (n_79), .Z (n_118));
  NR2M2R g4873__5526(.A (n_80), .B (n_79), .Z (n_119));
  NR2M2R g4858__6783(.A (waddr[3]), .B (n_78), .Z (n_122));
  NR2M2R g4875__3680(.A (n_28), .B (n_78), .Z (n_121));
  AOI222M1RA g4914__1617(.A1 (n_143), .A2 (\fifomem_mem[9] [3]), .B1
       (n_58), .B2 (\fifomem_mem[1] [3]), .C1 (n_156), .C2
       (\fifomem_mem[8] [3]), .Z (n_77));
  AOI222M1RA g4909__2802(.A1 (n_162), .A2 (\fifomem_mem[14] [6]), .B1
       (n_75), .B2 (\fifomem_mem[0] [6]), .C1 (n_54), .C2
       (\fifomem_mem[4] [6]), .Z (n_76));
  AOI222M1RA g4910__1705(.A1 (n_162), .A2 (\fifomem_mem[14] [7]), .B1
       (n_161), .B2 (\fifomem_mem[15] [7]), .C1 (n_88), .C2
       (\fifomem_mem[3] [7]), .Z (n_74));
  AOI222M1RA g4911__5122(.A1 (n_72), .A2 (\fifomem_mem[12] [5]), .B1
       (n_71), .B2 (\fifomem_mem[13] [5]), .C1 (n_92), .C2
       (\fifomem_mem[5] [5]), .Z (n_73));
  AOI222M1RA g4912__8246(.A1 (n_94), .A2 (\fifomem_mem[2] [2]), .B1
       (n_88), .B2 (\fifomem_mem[3] [2]), .C1 (n_147), .C2
       (\fifomem_mem[11] [2]), .Z (n_70));
  AOI222M1RA g4913__7098(.A1 (n_72), .A2 (\fifomem_mem[12] [1]), .B1
       (n_162), .B2 (\fifomem_mem[14] [1]), .C1 (n_92), .C2
       (\fifomem_mem[5] [1]), .Z (n_69));
  AOI222M1RA g4908__6131(.A1 (n_88), .A2 (\fifomem_mem[3] [4]), .B1
       (n_156), .B2 (\fifomem_mem[8] [4]), .C1 (n_72), .C2
       (\fifomem_mem[12] [4]), .Z (n_68));
  CKINVM1R g4890(.A (n_103), .Z (n_67));
  AOI222M1RA g4915__1881(.A1 (n_72), .A2 (\fifomem_mem[12] [0]), .B1
       (n_71), .B2 (\fifomem_mem[13] [0]), .C1 (n_92), .C2
       (\fifomem_mem[5] [0]), .Z (n_66));
  MOAI22M2RA g4916__7482(.A1 (n_65), .A2 (n_80), .B1 (n_65), .B2
       (n_80), .Z (n_135));
  MXB2M1RA g4871__4733(.A (raddr[3]), .B (n_3), .S (n_27), .Z (n_120));
  OAI211M2R g4870__6161(.A1 (n_10), .A2 (n_19), .B (n_18), .C (n_12),
       .Z (n_105));
  ND2M2R g4889__9315(.A (n_21), .B (waddr[1]), .Z (n_113));
  AOI22M2R g4928__9945(.A1 (n_75), .A2 (\fifomem_mem[0] [3]), .B1
       (n_88), .B2 (\fifomem_mem[3] [3]), .Z (n_64));
  AO22M1RA g4918__2883(.A1 (\fifomem_mem[9] [4]), .A2 (n_143), .B1
       (n_159), .B2 (\fifomem_mem[10] [4]), .Z (n_63));
  AO22M1RA g4919__2346(.A1 (\fifomem_mem[10] [1]), .A2 (n_159), .B1
       (n_147), .B2 (\fifomem_mem[11] [1]), .Z (n_62));
  AOI22M2R g4920__1666(.A1 (n_94), .A2 (\fifomem_mem[2] [3]), .B1
       (n_145), .B2 (\fifomem_mem[7] [3]), .Z (n_61));
  AO22M1RA g4921__7410(.A1 (\fifomem_mem[9] [5]), .A2 (n_143), .B1
       (n_159), .B2 (\fifomem_mem[10] [5]), .Z (n_60));
  AO22M1RA g4922__6417(.A1 (\fifomem_mem[1] [6]), .A2 (n_58), .B1
       (n_143), .B2 (\fifomem_mem[9] [6]), .Z (n_59));
  AOI22M2R g4923__5477(.A1 (n_75), .A2 (\fifomem_mem[0] [5]), .B1
       (n_145), .B2 (\fifomem_mem[7] [5]), .Z (n_57));
  AOI22M2R g4924__2398(.A1 (n_94), .A2 (\fifomem_mem[2] [4]), .B1
       (n_58), .B2 (\fifomem_mem[1] [4]), .Z (n_56));
  AOI22M2R g4925__5107(.A1 (n_54), .A2 (\fifomem_mem[4] [5]), .B1
       (n_58), .B2 (\fifomem_mem[1] [5]), .Z (n_55));
  AOI22M2R g4926__6260(.A1 (n_92), .A2 (\fifomem_mem[5] [2]), .B1
       (n_161), .B2 (\fifomem_mem[15] [2]), .Z (n_53));
  AOI22M2R g4927__4319(.A1 (n_156), .A2 (\fifomem_mem[8] [2]), .B1
       (n_143), .B2 (\fifomem_mem[9] [2]), .Z (n_52));
  AO22M1RA g4938__8428(.A1 (\fifomem_mem[4] [1]), .A2 (n_54), .B1
       (n_145), .B2 (\fifomem_mem[7] [1]), .Z (n_51));
  AO22M1RA g4929__5526(.A1 (\fifomem_mem[6] [0]), .A2 (n_99), .B1
       (n_88), .B2 (\fifomem_mem[3] [0]), .Z (n_50));
  AO22M1RA g4930__6783(.A1 (\fifomem_mem[14] [0]), .A2 (n_162), .B1
       (n_161), .B2 (\fifomem_mem[15] [0]), .Z (n_49));
  AO22M1RA g4931__3680(.A1 (\fifomem_mem[6] [5]), .A2 (n_99), .B1
       (n_88), .B2 (\fifomem_mem[3] [5]), .Z (n_48));
  AO22M1RA g4937__1617(.A1 (\fifomem_mem[6] [6]), .A2 (n_99), .B1
       (n_92), .B2 (\fifomem_mem[5] [6]), .Z (n_47));
  AO22M1RA g4936__2802(.A1 (\fifomem_mem[4] [4]), .A2 (n_54), .B1
       (n_71), .B2 (\fifomem_mem[13] [4]), .Z (n_46));
  AO22M1RA g4935__1705(.A1 (\fifomem_mem[4] [3]), .A2 (n_54), .B1
       (n_72), .B2 (\fifomem_mem[12] [3]), .Z (n_45));
  NR2M2R g4884__5122(.A (waddr[1]), .B (n_23), .Z (n_81));
  ND2M2R g4932__8246(.A (n_65), .B (waddr[2]), .Z (n_78));
  AOI21M2R g4933__7098(.A1 (n_17), .A2 (waddr[1]), .B (n_29), .Z
       (n_103));
  ND2M2R g4934__6131(.A (n_65), .B (n_25), .Z (n_107));
  CKINVM1R g4883(.A (n_104), .Z (n_44));
  AOI22M2R g4939__1881(.A1 (n_75), .A2 (\fifomem_mem[0] [1]), .B1
       (n_71), .B2 (\fifomem_mem[13] [1]), .Z (n_43));
  AOI22M2R g4940__5115(.A1 (n_94), .A2 (\fifomem_mem[2] [1]), .B1
       (n_58), .B2 (\fifomem_mem[1] [1]), .Z (n_42));
  AO22M1RA g4941__7482(.A1 (\fifomem_mem[12] [2]), .A2 (n_72), .B1
       (n_162), .B2 (\fifomem_mem[14] [2]), .Z (n_41));
  AOI22M2R g4942__4733(.A1 (n_71), .A2 (\fifomem_mem[13] [6]), .B1
       (n_161), .B2 (\fifomem_mem[15] [6]), .Z (n_40));
  AO22M1RA g4943__6161(.A1 (\fifomem_mem[4] [7]), .A2 (n_54), .B1
       (n_145), .B2 (\fifomem_mem[7] [7]), .Z (n_39));
  AO22M1RA g4944__9315(.A1 (\fifomem_mem[10] [7]), .A2 (n_159), .B1
       (n_147), .B2 (\fifomem_mem[11] [7]), .Z (n_38));
  AOI22M2R g4945__9945(.A1 (n_72), .A2 (\fifomem_mem[12] [6]), .B1
       (n_147), .B2 (\fifomem_mem[11] [6]), .Z (n_37));
  AOI22M2R g4946__2883(.A1 (n_75), .A2 (\fifomem_mem[0] [7]), .B1
       (n_71), .B2 (\fifomem_mem[13] [7]), .Z (n_36));
  AO22M1RA g4947__2346(.A1 (\fifomem_mem[13] [3]), .A2 (n_71), .B1
       (n_162), .B2 (\fifomem_mem[14] [3]), .Z (n_35));
  AOI22M2R g4948__1666(.A1 (n_75), .A2 (\fifomem_mem[0] [4]), .B1
       (n_145), .B2 (\fifomem_mem[7] [4]), .Z (n_34));
  AOI22M2R g4949__7410(.A1 (n_54), .A2 (\fifomem_mem[4] [0]), .B1
       (n_58), .B2 (\fifomem_mem[1] [0]), .Z (n_33));
  AO22M1RA g4950__6417(.A1 (\fifomem_mem[4] [2]), .A2 (n_54), .B1
       (n_58), .B2 (\fifomem_mem[1] [2]), .Z (n_32));
  AOI22M2R g4951__5477(.A1 (n_58), .A2 (\fifomem_mem[1] [7]), .B1
       (n_99), .B2 (\fifomem_mem[6] [7]), .Z (n_31));
  AOI22M2R g4952__2398(.A1 (n_75), .A2 (\fifomem_mem[0] [0]), .B1
       (n_145), .B2 (\fifomem_mem[7] [0]), .Z (n_30));
  ND2M2R g4877__5107(.A (n_29), .B (n_28), .Z (n_79));
  ND2M2R g4876__6260(.A (n_27), .B (raddr[3]), .Z (n_96));
  DFQRM2RA \wptr_full_wbin_reg[0] (.RB (wrst_n), .CK (wclk), .D (n_97),
       .Q (waddr[0]));
  ND2M2R g4881__4319(.A (n_29), .B (n_14), .Z (n_110));
  NR2M2R g4887__8428(.A (waddr[1]), .B (n_20), .Z (n_102));
  NR2M2R g4888__5526(.A (n_16), .B (n_26), .Z (n_109));
  NR2M2R g4879__6783(.A (waddr[1]), .B (n_26), .Z (n_106));
  ND2M2R g4880__3680(.A (n_29), .B (n_25), .Z (n_108));
  INVM1R g4892(.A (n_20), .Z (n_21));
  MAOI22M2RA g4886__1617(.A1 (n_19), .A2 (raddr[1]), .B1 (n_19), .B2
       (raddr[1]), .Z (n_104));
  CKND2M2R g4894__2802(.A (n_19), .B (raddr[2]), .Z (n_18));
  AO21M2RA g4956__1705(.A1 (n_4), .A2 (waddr[0]), .B (n_15), .Z (n_97));
  NR2M2R g4954__5122(.A (waddr[1]), .B (n_17), .Z (n_29));
  NR2M2R g4955__8246(.A (n_16), .B (n_17), .Z (n_65));
  ND2M2R g4901__7098(.A (n_15), .B (n_25), .Z (n_26));
  ND2M2R g4900__6131(.A (n_15), .B (n_14), .Z (n_20));
  ND2M2R g4899__1881(.A (n_15), .B (n_28), .Z (n_23));
  NR2M2R g4902__5115(.A (n_11), .B (n_19), .Z (n_27));
  MOAI22M2RA g4957__7482(.A1 (n_13), .A2 (raddr[0]), .B1 (n_13), .B2
       (raddr[0]), .Z (n_84));
  NR2M2R g4966__4733(.A (n_12), .B (n_5), .Z (n_71));
  NR2B1M2R g4965__6161(.B (n_6), .NA (n_7), .Z (n_156));
  NR2B1M2R g4964__9315(.B (n_12), .NA (n_9), .Z (n_54));
  NR2M2R g4971__9945(.A (n_11), .B (n_8), .Z (n_145));
  NR2B1M2R g4961__2883(.B (n_10), .NA (n_9), .Z (n_94));
  NR2M2R g4978__2346(.A (n_8), .B (n_12), .Z (n_92));
  NR2B1M2R g4973__1666(.B (n_8), .NA (n_7), .Z (n_58));
  NR2M2R g4974__7410(.A (n_11), .B (n_6), .Z (n_162));
  NR2M2R g4975__6417(.A (n_10), .B (n_8), .Z (n_88));
  NR2M2R g4976__5477(.A (n_10), .B (n_6), .Z (n_159));
  NR2M2R g4977__2398(.A (n_12), .B (n_6), .Z (n_72));
  NR2M2R g4972__5107(.A (n_10), .B (n_5), .Z (n_147));
  DFQRM2RA \sync_r2w_wq2_rptr_reg[4] (.RB (wrst_n), .CK (wclk), .D
       (sync_r2w_wq1_rptr[4]), .Q (wq2_rptr[4]));
  DFQRM2RA \sync_w2r_rq2_wptr_reg[4] (.RB (rrst_n), .CK (rclk), .D
       (sync_w2r_rq1_wptr[4]), .Q (rq2_wptr[4]));
  NR2B1M2R g4962__6260(.B (n_5), .NA (n_7), .Z (n_143));
  AN2M2R g4963__4319(.A (n_9), .B (n_7), .Z (n_75));
  ND2B1M2R g4960__8428(.B (waddr[0]), .NA (n_4), .Z (n_17));
  NR2M2R g4968__5526(.A (waddr[0]), .B (n_4), .Z (n_15));
  ND2B1M2R g4969__6783(.B (raddr[0]), .NA (n_13), .Z (n_19));
  NR2M2R g4970__3680(.A (n_11), .B (n_5), .Z (n_161));
  NR2B1M2R g4967__1617(.B (n_11), .NA (n_9), .Z (n_99));
  NR2M2R g4986__2802(.A (n_28), .B (n_80), .Z (n_14));
  NR2M2R g4987__1705(.A (waddr[2]), .B (n_28), .Z (n_25));
  CKND2M2R g4988__5122(.A (n_3), .B (raddr[0]), .Z (n_8));
  CKND2M2R g4989__8246(.A (n_2), .B (raddr[3]), .Z (n_6));
  CKND2M2R g4992__7098(.A (n_1), .B (raddr[1]), .Z (n_10));
  CKND2M2R g4991__6131(.A (n_0), .B (raddr[2]), .Z (n_12));
  DFQRM2RA \sync_w2r_rq1_wptr_reg[4] (.RB (rrst_n), .CK (rclk), .D
       (wptr[4]), .Q (sync_w2r_rq1_wptr[4]));
  DFQRM2RA \sync_r2w_wq1_rptr_reg[4] (.RB (wrst_n), .CK (wclk), .D
       (rptr[4]), .Q (sync_r2w_wq1_rptr[4]));
  ND2B1M2R g4981__1881(.B (winc), .NA (wfull), .Z (n_4));
  CKND2M2R g4985__5115(.A (raddr[2]), .B (raddr[1]), .Z (n_11));
  ND2B1M2R g4982__7482(.B (rinc), .NA (rempty), .Z (n_13));
  NR2M2R g4983__4733(.A (raddr[3]), .B (raddr[0]), .Z (n_9));
  NR2M2R g4984__6161(.A (raddr[2]), .B (raddr[1]), .Z (n_7));
  CKND2M2R g4990__9315(.A (raddr[0]), .B (raddr[3]), .Z (n_5));
  XNR2M2RA g2(.A (n_192), .B (wq2_rptr[4]), .Z (n_191));
  XOR2M2RA g5168(.A (n_121), .B (wptr[4]), .Z (n_192));
  DFRM2RA \wptr_full_wbin_reg[1] (.RB (wrst_n), .CK (wclk), .D (n_67),
       .Q (waddr[1]), .QB (n_16));
  DFRM2RA \wptr_full_wbin_reg[2] (.RB (wrst_n), .CK (wclk), .D (n_135),
       .Q (waddr[2]), .QB (n_80));
  DFRM2RA \wptr_full_wbin_reg[3] (.RB (wrst_n), .CK (wclk), .D (n_116),
       .Q (waddr[3]), .QB (n_28));
  DFRM2RA \rptr_empty_rbin_reg[0] (.RB (rrst_n), .CK (rclk), .D (n_84),
       .Q (raddr[0]), .QB (n_2));
  DFRM2RA \rptr_empty_rbin_reg[2] (.RB (rrst_n), .CK (rclk), .D
       (n_105), .Q (raddr[2]), .QB (n_1));
  DFRM2RA \rptr_empty_rbin_reg[1] (.RB (rrst_n), .CK (rclk), .D (n_44),
       .Q (raddr[1]), .QB (n_0));
  DFRM2RA \rptr_empty_rbin_reg[3] (.RB (rrst_n), .CK (rclk), .D (n_85),
       .Q (raddr[3]), .QB (n_3));
  ND2B1M2R g5183(.B (waddr[1]), .NA (n_23), .Z (n_193));
  NR3B1M2R g5184(.B (waddr[3]), .C (waddr[2]), .NA (n_65), .Z (n_194));
endmodule

